### ISSUE TITLE
WebAuthN not working while ZITADEL is behind an NGINX

### ISSUE THREAD

**Issue by lordwelch** [zitadel/zitadel#4307] opened 2022-09-05 02:25 UTC
**Describe the bug**
Cannot register a U2F token.

**To Reproduce**
1. Follow instructions from docker guide https://docs.zitadel.com/docs/guides/deploy/compose
2. Attempt to register any U2F token (tested: macOS fingerprint, OnlyKey Duo, YubiKey 5C NFC FW: 5.2.7, Android fingerprint)

**Expected behavior**
Successfully register a U2F token

**Screenshots**
<img width="454" alt="Screen Shot 2022-09-04 at 12 39 54 PM" src="https://user-images.githubusercontent.com/7547075/188330771-b2dcd463-d70a-49d7-ac60-dc001874d2ea.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Chrome, Safari, FireFox, Arc (based on chrome)
 - Version: 105.0.5195.102 (Official Build) (arm64), 103.0.2 (64-bit), Version 0.65.3 (34418) Chromium Engine Version 104.0.5112.102

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Browser: Chrome, FireFox
 - Version: 103.0.5060.114 (Official Build) Fedora Project (64-bit), 104.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11, OxygenOS version 11.1.1.1
 - Browser: Chrome, FireFox
 - Version: 104.0.5112.97, 104.1.0

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Browser: Chrome
 - Version: 105.0.5195.68

**Additional context**
Possibly related to #2910 #4082

**Comment by adlerhurst** [comment] 2022-09-06 09:14
Hi @lordwelch we shipped a [fix](https://github.com/zitadel/zitadel/pull/4290) lately but it is not yet available in the `stable`-tag. The bug should be fixed using `zitadel:latest`-image instead of `zitadel:stable`.

```yaml
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.1.3'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:
```

**Comment by lordwelch** [comment] 2022-09-08 06:51
This does indeed work, however I've made a minimal example based off of https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example
and it also fails webauthn, what do I need to do to make this work?
[zitadel.zip](https://github.com/zitadel/zitadel/files/9524377/zitadel.zip)

**Comment by livio-a** [comment] 2022-09-08 08:39
@lordwelch I've used your zip, (made en entry for narnian.us in my /etc/hosts) and i could setup U2F during login and passwordless in the console without any problem.

can you please check again?

**Comment by lordwelch** [comment] 2022-09-08 13:28
Here is the log and screenshot from when I attempt it
[docker.log](https://github.com/zitadel/zitadel/files/9527182/docker.log)
![image](https://user-images.githubusercontent.com/7547075/189134646-8829bc69-f5bf-433b-9eaa-8b70d1f44806.png)

**Comment by adlerhurst** [comment] 2022-09-09 08:40
thank you we will analyse the logs and come back to you asap

**Comment by fforootd** [comment] 2022-09-12 22:03
We also received reports for this issue to our support channels.
Lets look into this ASAP!

**Comment by fforootd** [comment] 2022-09-12 22:21
I just tested `Ubuntu 22.04.1 LTS` with the snap `firefox 104.0.2` in zitadel.cloud and it was working in console as well as in the login page.

Same result with MacOS and Safari. So it somewhat looks like a strange self-hosting issue.

**Comment by fforootd** [comment] 2022-09-12 22:30
@lordwelch can you share your nginx config? I think that could be an issue it somewhat looks like http2 is not working properly. But that is a wild guess :grin: 

A config that I know is working needs to inlcude this:

```
        location / {
            grpc_pass grpc://localhost:8080;
            grpc_set_header Host $host:$server_port;
        }
```

I just locally setup a new ZITADEL version 2.5.0 on my ubuntu and it worked flawless.

**Comment by lordwelch** [comment] 2022-09-12 23:05
@fforootd docker-compose example attached, fails on both macOS and Fedora 36
Or you can download the one in the edited post above and it has the cert in the zip as well.
[zitadel.zip](https://github.com/zitadel/zitadel/files/9552295/zitadel.zip)

**Comment by fforootd** [comment] 2022-09-12 23:12
I will try and run your exact example and see what it brings :grin:

**Comment by fforootd** [comment] 2022-09-12 23:37
Ok, finally I can reproduce it. Not sure what the problem is ATM

![image](https://user-images.githubusercontent.com/9879976/189776321-b21c8a15-2fe6-4c2f-a11a-a2a378f4b730.png)

**Comment by fforootd** [comment] 2022-09-13 00:15
This looks really like an odd encoding problem, or something like that.

**Comment by lordwelch** [comment] 2022-09-13 06:33
I've ran into those before, some of the most annoying bugs to track down, but not with Go.

**Comment by fforootd** [comment] 2022-09-13 06:59
> I've ran into those before, some of the most annoying bugs to track down, but not with Go.

Haha true, what I can see so far is that it does not work when ZITADEL is behind an NGINX, but when connecting to the same ZITADEL without NGINX it does work fine.

So it looks really like a config issue with the NGINX.

**Comment by stebenz** [comment] 2022-09-13 16:06
@lordwelch we found the reason for the confusion, if you use the origin "https://narnian.us:443", which is the host header provided by nginx, it's not equal to the configured origin to the webauthn library, which doesn't need the port information as https = 443.

So a quick solution for your problem is to change your nginx.conf to :
` grpc_set_header Host $host;`
not
`grpc_set_header Host $host:$server_port;`
As long as you use the default port for https.

We will change the examples and/or the code where necessary after we scoured the webauthn definition.
(FYI https://github.com/w3c/webauthn/issues/873 this topic was worked on already in some way)

**Comment by fforootd** [comment] 2022-09-13 16:31
Nice catch @stebenz !

**Comment by lordwelch** [comment] 2022-09-13 17:13
That fixed it! Thanks for the support!

**Comment by adlerhurst** [comment] 2022-09-13 17:14
Glad to hear that. We will leave the issue open to link the docs changes

**Comment by stebenz** [comment] 2022-09-15 15:29
changes the docs with the correct example and additional info

**Closed** 2022-09-15 15:38 UTC
Labels: type: bug, category: backend, priority: high
