### ISSUE TITLE
[Bug]: Display Identity Provider of External Org if Granted

### ISSUE THREAD

**Issue by hofq** [zitadel/zitadel#8463] opened 2024-08-20 14:55 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.51.3

### Database

PostgreSQL

### Database Version

zalando/spilo-16:3.2-p3

### Describe the problem caused by this bug

When I add another Organization as a Grant to a Project, the Identity Providers of the other Org will not be displayed on the Auth Page.

### To reproduce

1. Go to an exisiting project
2. Add another Existing Org as Grant, that has different idenity providers enabled than the current one
3. Save
4. Open the App connected to the Project
5. See only the Identity Providers of Main org, not the Granted one

### Expected behavior

I would want to see all Avalible Identity Providers (Either Merged or in a seperate area)

### Operating System

Device: Mac
OS: macOS Sonoma
Browser: Firefox 129.0.1

**Comment by hifabienne** [comment] 2024-08-26 08:34
Hi @hofq 
This is not a bug but works as intended.
A user always belongs to an organization and will authenticate with the possiblities configured on the organization.
If you redirect to the login of ZITADEL per default the settings of the default organization are shown. if you do want to change that, you can send the organization scope. urn:zitadel:iam:org:id:{id} 
https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

as soon as we have identified a user for example with the username, we also know to which organization the user belongs and are able to show the right settings. 

Additionally you can configure domain discovery to figure out where a user belongs by the domain: https://zitadel.com/docs/guides/solution-scenarios/domain-discovery

I will close this issue for now, as it is not a bug.

**Closed by hifabienne** 2024-08-26 08:34 UTC
Labels: bug

**Comment by hofq** [comment] 2024-08-26 15:12
Hi @hifabienne 

For me the Domain Discovery does not work as intended/ needed.

I have my main Org A on which i have made all identity providers and the login portal available. In my org B i have defined the ending domains of the email adresses of the users (b.example.com).

If a user logs in on the Login Portal (Which points to Org A, the Primary one) and creates a new user jane@b.example.com the user will be created in org A not in B.


How do i register new users with an external IDP in another org? I have enabled Domain Discovery everywhere.

**Comment by hifabienne** [comment] 2024-08-26 15:59
Is the domain on the org b verified?
It needs to have the check mark. 

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/ff8f96c9-e80d-4aa7-b023-d46fee255d3e">
