### ISSUE TITLE
[Bug]: Second factor SMS OTP can't be added on the org level

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7002] opened 2023-11-29 10:21 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Database

None

### Database Version

Postgres latest

### Describe the problem caused by this bug

SMS OTP is unusable on org level.

### To reproduce

1. Spin up a fresh environment from scratch
2. add SMS OTP via console to the org policy
3. Repeat, as it won't be listed
4. Note the already exists error

**Comment by hifabienne** [comment] 2023-11-29 12:30
@eliobischof as you already reproduced it, was it a frontend or backend issue?

**Comment by eliobischof** [comment] 2023-11-29 12:58
> @eliobischof as you already reproduced it, was it a frontend or backend issue?

Backend I think

**Comment by doncicuto** [comment] 2024-02-12 18:47
It seems that the issue also happens trying to add a Multifactor SMTP OPT for an org

![image](https://github.com/zitadel/zitadel/assets/30386061/3e6c9f6a-ed2d-4d91-b41d-d6efddc8d23f)

Maybe you can assign this to me @hifabienne

**Comment by eliobischof** [comment] 2024-02-27 11:16
@doncicuto thanks for offering your help with this! I assigned you.

**Comment by doncicuto** [comment] 2024-03-02 07:36
Hi @eliobischof and @hifabienne, I've tried to reproduce the issue again before working on the issue, but it seems that with the latest main code this is not happening anymore. Here's a video with a fresh backend compile and a new org:

https://github.com/zitadel/zitadel/assets/30386061/38ae7fb2-db4b-4409-adf1-1e1325f3afd1

If you can reproduce it again ping me :wink: I'm moving to another issue for now 

Cheers!

**Comment by hifabienne** [comment] 2024-03-04 08:14
Couldn't reproduce either. Will close the issue for now, if it reappears we can reopen.
@doncicuto Thanks for looking into it.

**Closed by hifabienne** 2024-03-04 08:14 UTC
Labels: bug, backend, resources
