### ISSUE TITLE
The error message for duplicate org name is not user friendly

### ISSUE THREAD

**Issue by dakshitha** [zitadel/zitadel#5342] opened 2023-03-03 05:23 UTC
**Acceptance Criteria**
- [ ] Error message with existing org is tranlated

### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

<img width="1440" alt="Screenshot 2023-03-03 at 10 43 44" src="https://user-images.githubusercontent.com/11885043/222637321-ca5ae3ca-f6be-498a-9b71-cf0e390f9096.png">

### To reproduce

When entering an existing organization name during sign up. 

### Expected behavior

"An organization with this name already exists." 

### Version

zitadel.cloud

### Operating System

Browser: Chrome

**Comment by ARSHIL1804** [comment] 2023-09-09 11:29
I would like to take this. @hifabienne  How can I replicate this on my local. I can't this kind of login page in zitadel repo

**Comment by hifabienne** [comment] 2023-09-11 06:54
Hei, this is acutally not possible to work on from your side, as this is not in zitadel itself, it is in our customer portal, which is not opensource. The issue is in the wrong repository.
But thanks for the offer.

**Comment by hifabienne** [comment] 2024-01-16 15:01
Will close this issue, as we have changed the onboarding flow

**Closed by hifabienne** 2024-01-16 15:01 UTC
Labels: bug, frontend
