### ISSUE TITLE
replace aggregate version with event version

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5355] opened 2023-03-03 17:42 UTC
There was a miss assumption while writing the first versions of the eventstore. Instead of versioning events aggregates were versioned. This issue is to get rid of these old burdens. 

As a ZITADEL developer using the eventstore framework, I want set a version of an event type instead of an aggregate type so that changing an event doesn't require to change the version of an aggregate. For backwards compatibility we have to deprecate the aggregate version first.

```[tasklist]
### Acceptance Criteria
- [x] `event_revision` column is added to the events table
- [ ] the event struct and interface use the new event version
- [ ] The events version uses the current version of the aggregate as a starting point
```

**Comment by hifabienne** [comment] 2023-10-17 15:07
duplicate of https://github.com/zitadel/zitadel/issues/5357 will close this one

**Closed by hifabienne** 2023-10-17 15:07 UTC
Labels: backend, technical-debt
