### ISSUE TITLE
[Bug]: No error checking if keys are empty

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#7206] opened 2024-01-11 21:19 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.43.4

### Database

PostgreSQL

### Database Version

14

### Describe the problem caused by this bug

This is the handler for the keys endpoint 
```https://zitadel.miab.mapped.dev/oauth/v2/keys```  

```go
func (s *LegacyServer) Keys(ctx context.Context, r *Request[struct{}]) (*Response, error) {
        // HERB: No Keys here
	keys, err := s.provider.Storage().KeySet(ctx)
	if err != nil {
		return nil, NewStatusError(err, http.StatusInternalServerError)
	}
	return NewResponse(jsonWebKeySet(keys)), nil
}

func (o *OPStorage) KeySet(ctx context.Context) (keys []op.Key, err error) {
	ctx, span := tracing.NewSpan(ctx)
	defer func() { span.EndWithError(err) }()
	err = retry(func() error {
               // HERB: No publicKeys here
		publicKeys, err := o.query.ActivePublicKeys(ctx, time.Now())
		if err != nil {
			return err
		}
		keys = make([]op.Key, len(publicKeys.Keys))
		for i, key := range publicKeys.Keys {
			keys[i] = &PublicKey{key}
		}
		return nil
	})
	return keys, err
}
func (q *Queries) ActivePublicKeys(ctx context.Context, t time.Time) (keys *PublicKeys, err error) {
	ctx, span := tracing.NewSpan(ctx)
	defer func() { span.EndWithError(err) }()

	query, scan := preparePublicKeysQuery(ctx, q.client)
	if t.IsZero() {
		t = time.Now()
	}
	stmt, args, err := query.Where(
		sq.And{
			sq.Eq{KeyColInstanceID.identifier(): authz.GetInstance(ctx).InstanceID()},
			sq.Gt{KeyPublicColExpiry.identifier(): t},
		}).ToSql()
	if err != nil {
		return nil, zerrors.ThrowInternal(err, "QUERY-SDFfg", "Errors.Query.SQLStatement")
	}

	err = q.client.QueryContext(ctx, func(rows *sql.Rows) error {
		keys, err = scan(rows)
		return err
	}, stmt, args...)
	if err != nil {
		return nil, zerrors.ThrowInternal(err, "QUERY-Sghn4", "Errors.Internal")
	}

	keys.State, err = q.latestState(ctx, keyTable)
	if !zerrors.IsNotFound(err) {
	       // HERB: No keys here.
		return keys, err
	}
	return keys, nil
}
```

I am getting no keys back and there is no error.
This is an error.    

Will try to hunt down the root cause.

 

### To reproduce

We setup a zitadel instance in docker several months back and saved the db.  When we come up from scratch its already setup.  

My theory is that this will be the base config and zitadel must cleanly migrate from it to the latest.  I also use this as a proof that if I had to restore a dated image of the database it should still work.  

The problem isn't with the latest version, it is there with the original one and things just stopped producing keys.  My hope was that upgrading would generate them again.

zitadel.yaml
```yaml
Port: 9999
ExternalPort: 443
ExternalSecure: true
ExternalDomain: zitadel.miab.mapped.dev

SystemDefaults:
  KeyConfig:
    PrivateKeyLifetime: 8760h
    PublicKeyLifetime: 1080h

Database:
  postgres:
    Host: postgresql
    Port: override_with_env_var
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: override_with_env_var
      Password: override_with_env_var
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username: override_with_env_var
      Password: override_with_env_var
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:

TLS:
  # Proxy deals with certificates
  # Cannot use them here because localhost heathcheck is not working with TLS.
  Enabled: false

```

init.yaml
```yaml
# This is used only for initialization.
# Right now zitadel is recovered from backup.
# This config here is for the case if something bad happens
# and we need to start from scratch
FirstInstance:
  MachineKeyPath: /machinekey/zitadel-admin-sa.json
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: ZITADEL
    Machine:
      Machine:
        Username: zitadel-admin-sa
        Name: Admin
      MachineKey:
        Type: 1
```

### Expected behavior

better, I got no keys mitigation.

### Operating System

Docker

**Comment by ghstahl** [comment] 2024-01-11 22:32
oddly enough I got into this at some point and it has a signing key.
```go
// SigningKey implements the op.Storage interface
func (o *OPStorage) SigningKey(ctx context.Context) (key op.SigningKey, err error) {
	err = retry(func() error {
		key, err = o.getSigningKey(ctx)
		if err != nil {
			return err
		}
		if key == nil {
			return zerrors.ThrowInternal(nil, "test", "test")
		}
		return nil
	})
	return key, err
}
```

**Comment by hifabienne** [comment] 2024-01-12 07:31
@livio-a @muhlemmer can you help here?

**Comment by muhlemmer** [comment] 2024-01-15 09:30
Can you check this discussion and answer and see if the same applies to your situation: https://github.com/zitadel/zitadel/discussions/7198

**Comment by ghstahl** [comment] 2024-01-15 13:57
Ok I get where the bug is.  
@muhlemmer "After a private key expires the new keypair is only created (ad-hoc) when a new token that needs to be signed is requested. (For example an ID token or access token as JWT)."

When a client makes a call to the JWKS enpoint Zitadel MUST return public keys.  It doesn't matter if anything has not yet used the private key to sign.  When someone ask you for something then give it to them.   

**_It is unacceptable to have an empty public key response._**

I would me that so called (ad-hoc) code to cover both cases.  

Also, this discussion, [Seamless JWKs rotation] (https://github.com/zitadel/zitadel/discussions/5690) cannot be ignored.  There is a reason your competitors have it. 

I guess I can get my devops guys to automate a login every 5 minutes to ensure that Zitadel creates keys.  :(

**Comment by muhlemmer** [comment] 2024-01-15 15:20
> It is unacceptable to have an empty public key response.

That's a matter of opinion, but not a valid bug report.

> Also, this discussion, https://github.com/zitadel/zitadel/discussions/5690 cannot be ignored. There is a reason your competitors have it.

Why even raise a bug if you are already part of the discussion regarding JWKs rotation. Put effort in the discussion, or come with a decent proposal or PR that solves a problem for you.

Voting to close @hifabienne, @livio-a  because:
- Currently behaves as designed.
- Current behavior is documented.
- Current behavior is explained in discussion: https://github.com/zitadel/zitadel/discussions/7198
- OP is already part of a discussion in changing the design https://github.com/zitadel/zitadel/discussions/5690

Alternatively this can be reshaped in a feature request and/or merged with the seamless design.

**Comment by ghstahl** [comment] 2024-01-15 16:17
BTW: Zitadel may fail OIDC specifications over this.

[oidc spec](https://openid.net/specs/openid-connect-core-1_0.html#toc)

I don't think there is carve out to say "we didn't use a private key to sign anything yet so no public keys".

I don't think it's a matter of opinion that keys MUST be returned even if nothing has been signed by their private key half.

```
15.2.  Mandatory to Implement Features for Dynamic OpenID Providers
In addition to the features listed above, OpenID Providers supporting dynamic establishment of relationships with RPs that they do not have a pre-configured relationship with MUST also implement the following features defined in this and related specifications.

Response Types
These OpenID Providers MUST support the id_token Response Type and all that are not Self-Issued OPs MUST also support the code and id_token token Response Types.
Discovery
These OPs MUST support Discovery, as defined in [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-core-1_0.html#OpenID.Discovery) [OpenID.Discovery].
Dynamic Registration
These OPs MUST support Dynamic Client Registration, as defined in [OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-core-1_0.html#OpenID.Registration) [OpenID.Registration].
UserInfo Endpoint
All dynamic OPs that issue Access Tokens MUST support the UserInfo Endpoint, as defined in [Section 5.3](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo). (Self-Issued OPs do not issue Access Tokens.)
Public Keys Published as Bare Keys
These OPs MUST publish their public keys as bare JWK keys (which MAY also be accompanied by X.509 representations of those keys).
Request URI
These OPs MUST support requests made using a Request Object value that is retrieved from a Request URI that is provided with the request_uri parameter, as defined in [Section 6.2](https://openid.net/specs/openid-connect-core-1_0.html#RequestUriParameter).
```

**Comment by muhlemmer** [comment] 2024-02-28 14:47
See this discussion for a proposal wrt key management:

- https://github.com/zitadel/zitadel/discussions/7464

**Comment by livio-a** [comment] 2024-03-20 07:30
closing in favor of the discussion mentioned above

**Closed by livio-a** 2024-03-20 07:30 UTC
Labels: bug, auth
