### ISSUE TITLE
[Bug]: post to /oauth/v2/revoke returns server error

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6320] opened 2023-08-03 16:12 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

Logs show that some requests on Aug 1 returned a 500 Error for put requests to /oauth/v2/revoke in the cloud service.

### To reproduce

Check logs for Aug 1. Further analysis of what caused the issue needs to be done.
<img width="165" alt="Screenshot 2023-08-03 at 18 12 30" src="https://github.com/zitadel/zitadel/assets/1366906/4cefdd04-97df-4bc8-a297-0cca66a27173">

### Expected behavior

Server should respond with an error message and not catch-all 500 exception.

**Comment by hifabienne** [comment] 2023-10-12 05:41
Will close this issue, as it is not possible to find out what the problem is anymore.

**Closed by hifabienne** 2023-10-12 05:41 UTC
Labels: bug
