### ISSUE TITLE
[Bug]: OneLogin IDP Integration

### ISSUE THREAD

**Issue by rajubish** [zitadel/zitadel#8260] opened 2024-07-06 13:02 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.2

### Database

CockroachDB

### Describe the problem caused by this bug

Hi,

We are using Zitadel for authorization and authentication in our portal and have integrated Azure SAML, Microsoft SSO, and Google SSO IDPs successfully. Now, we are integrating OneLogin SAML IDP. It redirects to OneLogin and after a successful login, it redirects back to our portal, but it throws the error “Errors.Intent.ResponseInvalid”.

Is there an issue with Zitadel for OneLogin SAML integration, or is there a misconfiguration on our side? What does this error mean?

Please help us resolve this issue as soon as possible.

Thanks

### To reproduce

Integrate OneLogin SAML Idp in zitadel setting.
Try to login with OneLogin.

### Screenshots

<img width="1650" alt="Screenshot 2024-07-06 at 6 19 47 PM" src="https://github.com/zitadel/zitadel/assets/74891056/39270c59-f768-41d4-a094-5fe583924c7d">

### Operating System

Device : Ubuntu 22.04
Browser: Google Chrome

**Comment by rajubish** [comment] 2024-07-09 02:45
Any update?

**Comment by livio-a** [comment] 2024-07-10 07:33
Hey @rajubish Can you please check the logs ("external authentication failed"). There should be some additional information about the error.

**Comment by rajubish** [comment] 2024-07-10 09:28
Hi @livio-a 
Please find below logs

time="2024-07-10T09:27:09Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:413" error="sql: transaction has already been committed or rolled back" projection=projections.org_members4
time="2024-07-10T09:27:10Z" level=info msg="external authentication failed" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/external_provider_handler.go:341" error="ID=SAML-nuo0vphhh9 Message=Errors.Intent.ResponseInvalid Parent=(Authentication failed)" instance=229834355738935297 providerID=275178372605149185
time="2024-07-10T09:27:10Z" level=warning msg="missing translation" args="map[]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/translator.go:161" error="message \"Errors.Intent.ResponseInvalid\" not found in language \"en\"" id=Errors.Intent.ResponseInvalid
time="2024-07-10T09:27:12Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:413" error="sql: transaction has already been committed or rolled back" projection=projections.org_members4

**Comment by rajubish** [comment] 2024-07-15 17:06
Waiting for update

**Comment by rajubish** [comment] 2024-07-17 11:45
Any update?

**Comment by hifabienne** [comment] 2024-07-18 08:44
not yet, we will need to have another look again

**Comment by rajubish** [comment] 2024-07-26 13:15
Any update?

**Comment by mario-shang** [comment] 2024-07-31 07:29
I think you can try updating the OneLogin SAML metadata.

**Comment by rajubish** [comment] 2024-07-31 07:31
What has to be update into SAML metadata?

**Comment by muhlemmer** [comment] 2024-07-31 07:44
Note to myself: add additional logging to establish the cause of the error.

**Comment by rajubish** [comment] 2024-08-05 02:56
Hi @muhlemmer 

Please find below response from one login and error in zitadel.

externalidp/callback?Method=POST&RelayState=279056240544342019&SAMLResponse=PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWw9InVybjpvYXNpczpuYW1lczp0%0D%0AYzpTQU1MOjIuMDphc3NlcnRpb24iIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6%0D%0AbmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIElEPSJSYzMxM2QyNjcwMDBh%0D%0AZWRjYzhiNDU5OTk2NzUyZWRiZDMwMzVkM2I3ZSIgVmVyc2lvbj0iMi4wIiBJ%0D%0Ac3N1ZUluc3RhbnQ9IjIwMjQtMDgtMDVUMDI6NTQ6NTdaIiBJblJlc3BvbnNl%0D%0AVG89ImlkLWZjYTM5MjZhNzgzNDZmZjhlNjkyODZlMzc1NzRkMDgwZTFjZWE0%0D%0AYWEiPjxzYW1sOklzc3Vlcj5odHRwczovL2FwcC5vbmVsb2dpbi5jb20vc2Ft%0D%0AbC9tZXRhZGF0YS8xZDMyYTVkOC02MjAyLTQ0ZGYtODkwYi0yOThkZjUwYTU3%0D%0AMDE8L3NhbWw6SXNzdWVyPjxzYW1scDpTdGF0dXM%2BPHNhbWxwOlN0YXR1c0Nv%0D%0AZGUgVmFsdWU9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpzdGF0dXM6%0D%0AU3VjY2VzcyIvPjwvc2FtbHA6U3RhdHVzPjxzYW1sOkFzc2VydGlvbiB4bWxu%0D%0AczpzYW1sPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9u%0D%0AIiB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEi%0D%0AIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEt%0D%0AaW5zdGFuY2UiIFZlcnNpb249IjIuMCIgSUQ9InBmeGM1MTEzY2E0LWNlOWYt%0D%0AYTQ4NS02ZTVkLTgyYzlmZDg0ZWM2OSIgSXNzdWVJbnN0YW50PSIyMDI0LTA4%0D%0ALTA1VDAyOjU0OjU3WiI%2BPHNhbWw6SXNzdWVyPmh0dHBzOi8vYXBwLm9uZWxv%0D%0AZ2luLmNvbS9zYW1sL21ldGFkYXRhLzFkMzJhNWQ4LTYyMDItNDRkZi04OTBi%0D%0ALTI5OGRmNTBhNTcwMTwvc2FtbDpJc3N1ZXI%2BPGRzOlNpZ25hdHVyZSB4bWxu%0D%0Aczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI%2BPGRz%0D%0AOlNpZ25lZEluZm8%2BPGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3Jp%0D%0AdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMi%0D%0ALz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53%0D%0AMy5vcmcvMjAwMC8wOS94bWxkc2lnI3JzYS1zaGExIi8%2BPGRzOlJlZmVyZW5j%0D%0AZSBVUkk9IiNwZnhjNTExM2NhNC1jZTlmLWE0ODUtNmU1ZC04MmM5ZmQ4NGVj%0D%0ANjkiPjxkczpUcmFuc2Zvcm1zPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJo%0D%0AdHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNp%0D%0AZ25hdHVyZSIvPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3%0D%0ALnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9y%0D%0AbXM%2BPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMu%0D%0Ab3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8%2BPGRzOkRpZ2VzdFZhbHVlPlY1%0D%0ANHJxeTNWd2Fwc24wS2t0WGYwSU1vY010UT08L2RzOkRpZ2VzdFZhbHVlPjwv%0D%0AZHM6UmVmZXJlbmNlPjwvZHM6U2lnbmVkSW5mbz48ZHM6U2lnbmF0dXJlVmFs%0D%0AdWU%2BWWEwSlYyOUoyMjdZKzRuZmRrRnpnbDJoOGtYK25GTU9nZFhSUXZkZVJR%0D%0ATHd0bnZFM2tqSnRsV0Rab1ZmWiszUmd6eFlFZkI4K0k4ZWZNaVdTRVg2OTZB%0D%0AQ2RqdlN6OGZEZlJHdEdXYmFsWUkzN2NNbXRDc3A4aXYzd0xPZlJMdlc5bnVy%0D%0AYUUrSHJsZ2ZSUE8zQ294cG1TcXh5anBRRE9RaUVKRDNETjhwbU11Q2szUXE5%0D%0AaEhjQkxVK3ArSFR3UDM3Ri9FSXUrdTVEVnh5WHp1RlNUZU52ZUtUckpOUUdX%0D%0AUzNDM3liRjhJQUtmaXEzN1pBNDR6c1cxYWRtWmc4RjlaTmMzaEt2KzJoN3lU%0D%0AQU5aS3BkN3M1S3ZreVltb2J4c21oRFhTWmdlSWtJRVNhNWVhckZ0YU5SRllJ%0D%0ARzFLN0taNWhGYVlycnRhS1VWV21XNlJaNFcyV1hnPT08L2RzOlNpZ25hdHVy%0D%0AZVZhbHVlPjxkczpLZXlJbmZvPjxkczpYNTA5RGF0YT48ZHM6WDUwOUNlcnRp%0D%0AZmljYXRlPk1JSUQ3akNDQXRhZ0F3SUJBZ0lVRkxzVmNXVVJKdE9BNGRmazZi%0D%0AdDFBU1p2MUw0d0RRWUpLb1pJaHZjTkFRRUZCUUF3U3pFV01CUUdBMVVFQ2d3%0D%0ATlEyOXVibVZqZEZObFkzVnlaVEVWTUJNR0ExVUVDd3dNVDI1bFRHOW5hVzRn%0D%0AU1dSUU1Sb3dHQVlEVlFRRERCRlBibVZNYjJkcGJpQkJZMk52ZFc1MElEQWVG%0D%0AdzB5TkRBM01Ea3dOREkxTXpGYUZ3MHlPVEEzTURrd05ESTFNekZhTUVzeEZq%0D%0AQVVCZ05WQkFvTURVTnZibTVsWTNSVFpXTjFjbVV4RlRBVEJnTlZCQXNNREU5%0D%0AdVpVeHZaMmx1SUVsa1VERWFNQmdHQTFVRUF3d1JUMjVsVEc5bmFXNGdRV05q%0D%0AYjNWdWRDQXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtB%0D%0Ab0lCQVFETDMxZHZtakdVa0pmV1dETjU5djNGZElxSXdDTzJONHc0a240bHRG%0D%0AOTQwRUFVbWtuN204Q21zWXZ4M0dxQlJLZDhpU1BaNmZUWkxRbDJHYytTRVhY%0D%0AVlJDUG1RanVCdHZ4azVXVXF1RTU0eTE3ODk2M3VjNGhTaURHdU0wbG1xVXdI%0D%0AYm9aN25nYnBjNnk5RFdRL2xIcDBLbTRGOVNac1FVZ0hXRTVLVUN4elJxdnhM%0D%0ARjZVa0YyNk82bmpVc3NHRjFmVTA3Uy81M1VkL3gvMUR5STlsalBpc25rTUhr%0D%0AYkNMYXVDVFlNOURMRmNjQjNPbDV4cEhaOTdkK0drbXVQM2RoUTBkMVR4NGlJ%0D%0AZU1PWkV5TWFYeDN3TTN6ekk2SzVvdVRtMTIwRlBaOUdwbzN0SWVtVXc3SEFE%0D%0AV3lBQlB2YXNpdGVxMFR1Zm9MeGoyeEQxaHFvSDZMVk5BZ01CQUFHamdja3dn%0D%0AY1l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVRL1Zxckt0VW02%0D%0AQ2lrY3VnNVRuMnBWWlNzZ1F3Z1lZR0ExVWRJd1IvTUgyQUZFUDFhcXlyVkp1%0D%0AZ29wSExvT1U1OXFWV1VySUVvVStrVFRCTE1SWXdGQVlEVlFRS0RBMURiMjV1%0D%0AWldOMFUyVmpkWEpsTVJVd0V3WURWUVFMREF4UGJtVk1iMmRwYmlCSlpGQXhH%0D%0AakFZQmdOVkJBTU1FVTl1WlV4dloybHVJRUZqWTI5MWJuUWdnaFFVdXhWeFpS%0D%0ARW0wNERoMStUcHUzVUJKbS9VdmpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RFFZ%0D%0ASktvWklodmNOQVFFRkJRQURnZ0VCQUhNM0IxU0dkdkdLTmU2N3YrY3lHcW00%0D%0ANWVqb05lTmxWbjVzWnRMK1NSUUg1SnRuZUpRVlJYQzRZYlpRVzViS1U2U1Ji%0D%0AQzZBcDJUeVJKUjZ0SjhpQlVKaXlCMXRhYXNmTHhXc2d2djRCbktjUFh2Sm5m%0D%0AdGdrbnYwbTdOdFdWLzVLTVRxQlBSemV0NkI0enp0NFRnOW9wM215SDZIZUFn%0D%0AR1lvSjJ6eFhtR1NzeitRODhudXk0bnI2eXNvOXJJTld1T21QMUVjZHYrWU1K%0D%0AQmh3U1M3Q1kwdThWdlZhMzNzTjhrUGNTZVdxOExZQmxEYXpnaVVOckZ0YW9E%0D%0AdDl5RHk3U1prcUkyRkdOMVV5aEJHMVNQS3IxOGVvUVBqdUwzdElDaEIvaVNI%0D%0ATFcwczhxdWdYSkN4bGxTTHBRUml5NENQZUhqempPZnZTS1p3dUFtaUI2bDZN%0D%0AN2JOUT08L2RzOlg1MDlDZXJ0aWZpY2F0ZT48L2RzOlg1MDlEYXRhPjwvZHM6%0D%0AS2V5SW5mbz48L2RzOlNpZ25hdHVyZT48c2FtbDpTdWJqZWN0PjxzYW1sOk5h%0D%0AbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1l%0D%0AaWQtZm9ybWF0OmVtYWlsQWRkcmVzcyI%2BcmFqdWJAY29ubmVjdHNlY3VyZS5j%0D%0Ab208L3NhbWw6TmFtZUlEPjxzYW1sOlN1YmplY3RDb25maXJtYXRpb24gTWV0%0D%0AaG9kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6Y206YmVhcmVyIj48%0D%0Ac2FtbDpTdWJqZWN0Q29uZmlybWF0aW9uRGF0YSBOb3RPbk9yQWZ0ZXI9IjIw%0D%0AMjQtMDgtMDVUMDI6NTc6NTdaIiBSZWNpcGllbnQ9IiIgSW5SZXNwb25zZVRv%0D%0APSJpZC1mY2EzOTI2YTc4MzQ2ZmY4ZTY5Mjg2ZTM3NTc0ZDA4MGUxY2VhNGFh%0D%0AIi8%2BPC9zYW1sOlN1YmplY3RDb25maXJtYXRpb24%2BPC9zYW1sOlN1YmplY3Q%2B%0D%0APHNhbWw6Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMjQtMDgtMDVUMDI6NTE6%0D%0ANTdaIiBOb3RPbk9yQWZ0ZXI9IjIwMjQtMDgtMDVUMDI6NTc6NTdaIj48c2Ft%0D%0AbDpBdWRpZW5jZVJlc3RyaWN0aW9uPjxzYW1sOkF1ZGllbmNlLz48L3NhbWw6%0D%0AQXVkaWVuY2VSZXN0cmljdGlvbj48L3NhbWw6Q29uZGl0aW9ucz48c2FtbDpB%0D%0AdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMjQtMDgtMDVUMDI6NTQ6%0D%0ANTZaIiBTZXNzaW9uTm90T25PckFmdGVyPSIyMDI0LTA4LTA2VDAyOjU0OjU3%0D%0AWiIgU2Vzc2lvbkluZGV4PSJfZDFlNzhjYzctZjViOC00NzAxLTgzM2YtNWU1%0D%0AMTQwYzM3ZjllIj48c2FtbDpBdXRobkNvbnRleHQ%2BPHNhbWw6QXV0aG5Db250%0D%0AZXh0Q2xhc3NSZWY%2BdXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNs%0D%0AYXNzZXM6UGFzc3dvcmRQcm90ZWN0ZWRUcmFuc3BvcnQ8L3NhbWw6QXV0aG5D%0D%0Ab250ZXh0Q2xhc3NSZWY%2BPC9zYW1sOkF1dGhuQ29udGV4dD48L3NhbWw6QXV0%0D%0AaG5TdGF0ZW1lbnQ%2BPHNhbWw6QXR0cmlidXRlU3RhdGVtZW50PjxzYW1sOkF0%0D%0AdHJpYnV0ZSBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoy%0D%0ALjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIiBOYW1lPSJGaXJzdE5hbWUiPjxz%0D%0AYW1sOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5v%0D%0AcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTpuaWw9InRydWUiIHhz%0D%0AaTp0eXBlPSJ4czpzdHJpbmciLz48L3NhbWw6QXR0cmlidXRlPjxzYW1sOkF0%0D%0AdHJpYnV0ZSBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoy%0D%0ALjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIiBOYW1lPSJFbWFpbCI%2BPHNhbWw6%0D%0AQXR0cmlidXRlVmFsdWUgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8y%0D%0AMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOm5pbD0idHJ1ZSIgeHNpOnR5%0D%0AcGU9InhzOnN0cmluZyIvPjwvc2FtbDpBdHRyaWJ1dGU%2BPHNhbWw6QXR0cmli%0D%0AdXRlIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDph%0D%0AdHRybmFtZS1mb3JtYXQ6YmFzaWMiIE5hbWU9IlVzZXJuYW1lIj48c2FtbDpB%0D%0AdHRyaWJ1dGVWYWx1ZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIw%0D%0AMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6bmlsPSJ0cnVlIiB4c2k6dHlw%0D%0AZT0ieHM6c3RyaW5nIi8%2BPC9zYW1sOkF0dHJpYnV0ZT48c2FtbDpBdHRyaWJ1%0D%0AdGUgTmFtZUZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmF0%0D%0AdHJuYW1lLWZvcm1hdDpiYXNpYyIgTmFtZT0iTGFzdE5hbWUiPjxzYW1sOkF0%0D%0AdHJpYnV0ZVZhbHVlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAw%0D%0AMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTpuaWw9InRydWUiIHhzaTp0eXBl%0D%0APSJ4czpzdHJpbmciLz48L3NhbWw6QXR0cmlidXRlPjwvc2FtbDpBdHRyaWJ1%0D%0AdGVTdGF0ZW1lbnQ%2BPC9zYW1sOkFzc2VydGlvbj48L3NhbWxwOlJlc3BvbnNl%0D%0APgoK%0D%0A

<img width="618" alt="image" src="https://github.com/user-attachments/assets/f1d63abc-0293-46c4-a31e-8ed8430ee9ea">

**Comment by stebenz** [comment] 2024-08-16 13:00
Hi @rajubish 
So I just tried it with OneLogin and it worked without a problem, I used the following configuration:

![Image](https://github.com/user-attachments/assets/04ecba53-9b17-481c-b6a9-839334b6ea0d)

Can you have a look and tell me if there are any differences in your configuration?

**Comment by rajubish** [comment] 2024-08-18 07:40
Hi @stebenz 

I updated the configuration as per you attachment, now it's redirecting to create account page but values are not prefilled.

<img width="941" alt="image" src="https://github.com/user-attachments/assets/3d340c14-a539-4dc6-8a00-4f58f5470118">

I added below code in zitadel action postauthentication.
function prefilRegisterFromOKTASAML(ctx, api) {
	if (ctx.v1.externalUser.externalIdpId != "<SAML IDP ID>") {
        return
    }
    // the attribute names below represent a attribute statement with basic format (configured in OKTA App)
    let firstname = ctx.v1.providerInfo.attributes["FirstName"];
    let lastname = ctx.v1.providerInfo.attributes["LastName"];
    let email = ctx.v1.providerInfo.attributes["Email"];
    let username = ctx.v1.providerInfo.attributes["Email"];
    if (firstname != undefined) {
    	api.setFirstName(firstname[0]);
    }
    if (lastname != undefined) {
	    api.setLastName(lastname[0]);
    }
    if (email != undefined) {
    	api.setEmail(email[0]);
	    api.setEmailVerified(true);
    }
    if (username != undefined) {
	    api.setPreferredUsername(username[0]);
    }    
}

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/52803a01-2f29-4d3e-a10b-69e3414dae29">

Anything is missing or wrong here?

**Comment by muhlemmer** [comment] 2024-08-20 14:49
Thanks for the help @stebenz!

Closing this issue, as there is no bug. I want to prevent this becoming a support discussion. Either use Discord, Github discussions for community support. Or consider buying commercial support from zitadel.

**Closed** 2024-08-20 14:50 UTC
Labels: bug, auth
