### ISSUE TITLE
How to get smtp token ?

### ISSUE THREAD

**Issue by BJorah** [zitadel/zitadel#8323] opened 2024-07-17 03:48 UTC
I use docker-compose on my server to build ,refering to this mothod: https://docs.netbird.io/selfhosted/selfhosted-quickstart, The Idp I use is zitadel
 I use email address to create a new user, but I cann't receive the email.
<img width="440" alt="04abc23a8fddbc6ca77bcccc4cf3633" src="https://github.com/user-attachments/assets/09b55be3-77d3-4e0d-b138-82ff53d4204b">
<img width="403" alt="8c9e2b3a973b1d099b608cbdbf9d85c" src="https://github.com/user-attachments/assets/c386c301-218c-4285-a7f7-7547cf4fc35f">

the devoloper told me I should config the SMTP,  link is here :https://zitadel.com/docs/apis/resources/admin/smtp,  but I have no idea **how to get the Token**  as shown below ?

Can anyone tell me how to get the token? Thanks a lot.

<img width="879" alt="4c954c7e6ea5e1f81381717c435cb7c" src="https://github.com/user-attachments/assets/43c98cc4-f6b5-40ab-8a62-781649260778">

**Comment by hifabienne** [comment] 2024-07-17 05:30
Hei @BJorah 
When you setup your instance you set it up with a first user, this is either a human or a machine.
If you have a human you can also login to the console and change the smtp there. 
your-instance/ui/console/

if you have a machine you will get a PAT personal access token, which is a ready to use token, you will get it in the configured path on your root.

**Comment by BJorah** [comment] 2024-07-17 06:25
> Hei @BJorah When you setup your instance you set it up with a first user, this is either a human or a machine. If you have a human you can also login to the console and change the smtp there. your-instance/ui/console/
> 
> if you have a machine you will get a PAT personal access token, which is a ready to use token, you will get it in the configured path on your root.

I have a machine ,my server , the zitadel is running in docker on the server,  could you  please tell me specific path of "the configured path on your root." ？ I do not quite understand what it means.
![image](https://github.com/user-attachments/assets/e7360845-5855-4afe-aff2-2eec1743d59f)

**Comment by BJorah** [comment] 2024-07-17 07:03
> Hei @BJorah When you setup your instance you set it up with a first user, this is either a human or a machine. If you have a human you can also login to the console and change the smtp there. your-instance/ui/console/
> 
> if you have a machine you will get a PAT personal access token, which is a ready to use token, you will get it in the configured path on your root.

Do you mean this one ?   
![image](https://github.com/user-attachments/assets/31f13361-6384-4f36-a352-9092f39bd272)
![image](https://github.com/user-attachments/assets/9b6d334f-5abc-4ebc-a501-0d8f3e8d9b83)
 
I tried this.However it doesn't work , it's wrong. 
![image](https://github.com/user-attachments/assets/2bc5e01f-6cc3-41d4-9ed6-e4f42bb1b207)

**Comment by hifabienne** [comment] 2024-07-17 10:40
yes. @stebenz @eliobischof can you help here?

**Comment by BJorah** [comment] 2024-07-19 09:40
hei! @hifabienne 
I tried another way to send email. In the docker-compose.yml, I add these message to the **zitadel.env** , and then start the docker
![image](https://github.com/user-attachments/assets/ce7c721d-e66e-4c92-bb4f-cc6dccbeece0)
![image](https://github.com/user-attachments/assets/8274608b-0bfe-4cfd-9383-b7f2c985b0f4)
![img_v3_02cu_200ae7dc-cf79-4ec4-81db-82d226d6b7fg](https://github.com/user-attachments/assets/858cb68d-29d5-45bb-bc15-8ffc7d63c6c2)

But I when I register a new user ,I still cann't receive the activate email code 
Am I do right ? 
Would you please tell me how to config the smtp so that my server can sent email ?

**Comment by hifabienne** [comment] 2024-07-22 05:34
Do you get any error logs?
@eliobischof can you help here?

**Comment by BJorah** [comment] 2024-07-22 06:27
There is something amazing that I rebuild a new one without any change follow the guide there https://docs.netbird.io/selfhosted/selfhosted-quickstart ,  
and then, I visited https://yourdomain.com/ui/console/instance?id=smtpprovider 
I driectly went into this page without resquesting me to put in any password or emil code.  As a result I add my own smtp config here and now I am able to receive the email to add new users.
![image](https://github.com/user-attachments/assets/f76974f7-538e-4b84-9e4e-8250e8ef26c6)

**Comment by hifabienne** [comment] 2024-07-22 06:35
Great to hear that you got it running.
I think now I saw something that might be the problem, so the settings in the yaml, are only added on the first creation of the instance as far as i know.
did you setup a new instance, or did you want to apply it on an existing instance?

**Comment by BJorah** [comment] 2024-07-22 06:51
> 很高兴听到您让它运行起来。 我认为现在我看到了可能存在问题的地方，所以据我所知，yaml 中的设置仅在第一次创建实例时添加。 您设置了新实例，还是想将其应用于现有实例？
I consider that I didn't add a new instance, I just apply the smpt it on the the yaml created one.

**Comment by BJorah** [comment] 2024-07-22 07:17
In this way the new users I added are put into the group under the first created instance . However that isn't all I wanted . 
What I want to realize is that I can create new instance on the server.

**Comment by hifabienne** [comment] 2024-07-22 07:53
So to test if it works or not you either need to remove the whole setup and setup again, or you can add a new instance through the system api, be aware if you use the system api, you will also need a system user with token. 
https://zitadel.com/docs/apis/resources/system/system-service-create-instance

**Comment by stebenz** [comment] 2024-11-11 14:45
I will close this issue as it seems that the problem is solved.

Just to reiterate, changed values through environment variables or in the configuration-yaml directly only apply for either newly created instances or at setup, which would most of the time mean that you have to destroy and re-setup.
You can change the values directly in the configuration, but if you then re-setup, the values are back to default.

**Closed by stebenz** 2024-11-11 14:45 UTC
Labels: devops
