### ISSUE TITLE
[Bug]: _is_unique method in management API returns empty payload

### ISSUE THREAD

**Issue by aalexren** [zitadel/zitadel#6114] opened 2023-06-28 18:02 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.28.1

### Describe the problem caused by this bug

In the documentation this method says that it returns boolean value, but actually it returns only True if not exists and nothing if exists: https://zitadel.com/docs/apis/resources/mgmt/management-service-is-user-unique

I think this shouldn't be a appropriate behaviour

### To reproduce

1. Create service "super" user
2. Create PAT token for him
3. Create common user with username and email
4. Try to make request as shown here: https://zitadel.com/docs/apis/resources/mgmt/management-service-is-user-unique
4.1. Make sure you've passed username and email
4.2 Sure that it returns empty body

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/25721843/67e277e6-3863-4a94-b76d-89a9c872120f)

### Expected behavior

As I expected if user exists this method should return json with "isUnique" parameter in True value.

### Operating System

Device: Macbook Air 2015 13'
OS: macOS 12.6.7 Monterey
Browser: CURL
Version: 7.87

**Comment by hifabienne** [comment] 2023-06-29 05:56
Hei @aalexren 
This is not a bug and works as intended.
We do not serialise the default values as they will be interpreted by the client as default values anyway.
This saves some unnecessary traffic when sending the response.
In your case the default value of the bool is false, and will not be sent.
We will have a look at if this can be designed better in the future.

**Closed by hifabienne** 2023-06-29 05:56 UTC
Labels: bug
