### ISSUE TITLE
Improper domains for unicode-only organizations

### ISSUE THREAD

**Issue by kraney** [zitadel/zitadel#6622] opened 2023-09-25 17:25 UTC
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When an organization name includes only spaces and unicode characters (like 这不起作用) the resulting autogenerated domain name is nonfunctional. The algorithm doesn't handle repeated spaces or dashes and drops the unicode characters without any replacement to keep things unique.

### Describe your ideal solution

Preferably internationalized domain names should be supported. https://unicode.org/faq/idn.html

### Environment

Self-hosted

**Comment by doncicuto** [comment] 2023-10-07 10:02
Hi @hifabienne, maybe a duplicate of #6471 so one of these can be closed?

**Comment by hifabienne** [comment] 2023-10-09 06:56
Hei @doncicuto 
Yes you are right, I will close this one.

**Closed by hifabienne** 2023-10-09 06:56 UTC
Labels: improvement
