### ISSUE TITLE
[Bug]: Service users on default org do not have a client ID

### ISSUE THREAD

**Issue by thaddeuskkr** [zitadel/zitadel#8815] opened 2024-10-23 07:56 UTC
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.64.1

### Database

PostgreSQL

### Database Version

PostgreSQL 16.4

### Describe the problem caused by this bug

Creating a service user on the default organisation `ZITADEL` causes the service user not to have a client ID (and no login methods). When generating a client secret, there is also no client ID passed back. Comparatively, when creating a service user on another organisation, creating the service user also creates a login method, and when generating a client secret, a client ID is passed back.

### To reproduce

1. Go to the ZITADEL default organisation
2. Create a service user (any name, any access token type)
3. Notice that there are no login methods (screenshot attached)
4. Generate a client secret (via Actions)
5. Notice that no client ID shows up (screenshot attached)
6. Go to another organisation
7. Create another service user (any name, any access token type)
8. Notice that a login method appears
9. Generate a client secret (via Actions)
10. Notice that a client ID shows up (screenshot attached)

### Screenshots

![Image](https://github.com/user-attachments/assets/38f499ed-bdfa-4e0a-92e9-8139026e6908)
![Image](https://github.com/user-attachments/assets/a7008dce-462e-4571-b361-90ee18571590)
![Image](https://github.com/user-attachments/assets/7620f405-af80-46c7-8ccc-6fd7bf7c1f67)
![Image](https://github.com/user-attachments/assets/7693145b-4866-433f-ad25-5e0c5af6a522)

### Expected behavior

A login method should be created for the service user created on the default ZITADEL organisation.

### Operating System

ZITADEL is running via Docker Compose, proxied behind Caddy.

**Comment by thaddeuskkr** [comment] 2024-10-23 08:19
I deleted the database and created a new instance, and this issue was fixed.

Though I think this is worth looking into. I have a backup of my previous database and settings if required.

**Comment by hifabienne** [comment] 2024-10-25 12:54
Hi @thaddeuskkr 
I checked this on our cloud service and couldn't reproduce the issue.
Did you also experience some other problems?

**Comment by thaddeuskkr** [comment] 2024-10-30 03:31
> Did you also experience some other problems?

Nope, that was the only issue I faced.

**Comment by hifabienne** [comment] 2024-10-30 06:30
I will close the issue for now, if we see it appearing again we will have a look.

**Closed by hifabienne** 2024-10-30 06:30 UTC
Labels: bug, resources
