### ISSUE TITLE
[Bug]: Wrong organization id and name in granted projects

### ISSUE THREAD

**Issue by m-arre** [zitadel/zitadel#7097] opened 2023-12-19 17:29 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.0

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

As shown in the screenshot, when a project is granted from an organization A to an organization B, and a authorization is created for a user in the organization B, the resulting org_id, org_name and org_domain are equal to organization B ones, instead of A.

The same happens using the `/usergrants/me/_search` endpoint.

### To reproduce

Steps to reproduce the behaviour:
1) Grant a project to another organization
2) Create an authorization in the second organization for that project

### Screenshots

![Schermata del 2023-12-19 18-17-33](https://github.com/zitadel/zitadel/assets/37012920/38f76bbe-7fab-4e62-8441-6be8b1c91662)

**Comment by hifabienne** [comment] 2023-12-20 07:20
Hi
This is not a bug it works as intended. You will always get the organization back where the user got the grant.
If you want to get back the Organization A, you will have to grant the user in organization A

**Comment by hifabienne** [comment] 2024-01-15 09:18
As I din't hear anything back. I will close this issue.
Feel free to reopen, when you can add more information about your use case.

**Closed by hifabienne** 2024-01-15 09:18 UTC
Labels: bug
