### ISSUE TITLE
Console UI/UX elements for smaller screens

### ISSUE THREAD

**Issue by rundx** [zitadel/zitadel#6008] opened 2023-06-11 13:23 UTC
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I don't know if this is just me but does anyone feel like Console UI/UX elements are huge for smaller screens 
I'm using a 15 retina macbook and console feels a little bit better when I reduce zoom to 90% on firefox

### Describe your ideal solution

I think maybe Zitadel console needs a UI/UX revamp

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment] 2023-06-12 12:51
Hei @rundx 
Thanks for the issue. Can you maybe add some screenshots to show where you feel the screen doesn't fit?
For now I will put the issue into the product backlog as we didn't hear any other problems so far.

**Comment by hifabienne** [comment] 2023-09-11 12:22
As we didn't get any feedback, and can't verify where the problem is, I will close the issue for now.
Feel free to reopen, if you add additional information.

**Closed by hifabienne** 2023-09-11 12:22 UTC
Labels: improvement
