### ISSUE TITLE
Changing language on instance level doesn't work.

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4671] opened 2022-11-07 11:40 UTC
**Describe the bug**
Changing an instances language after from scratch installation doesn't work. The console instead prints an error about missing SMTP settings. 

**To Reproduce**
1. Install ZITADEL from scratch
2. Go to instance general settings
3. Change language
4. Refresh

**Expected behavior**
Language is changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/12727842/200300244-a303e357-3c07-4948-b8fe-d718fe1d20ae.png)

**Comment by hifabienne** [comment] 2022-11-07 15:13
I tried this on my ZITADEL cloud instance. And I can't reproduce it. @eliobischof can you see what requests are done?
The setting is changed correctly. Only problem the loading icon doesn't disappear after.



![Image](https://user-images.githubusercontent.com/38692350/200345274-8573db31-2939-4c03-b506-4bebf02c50ea.png)

**Comment by eliobischof** [comment] 2022-11-08 13:58
The instance language is new users default language. The users language defines how the console is displayed. Therefore works as expected, apart from the spinner (PR is linked).

**Comment by peintnermax** [comment] 2022-11-08 14:34
spinner is fixed with #4676

**Closed** 2022-11-14 15:41 UTC
Labels: type: bug, state: triage
