### ISSUE TITLE
[Bug]: Login button on completed logout leads to console

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7381] opened 2024-02-13 14:47 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

https://b2b-demo-rbxajm.zitadel.cloud/ui/login/logout/done

When i click on the "Login" button then I am prompted to login to the console (action in the form points to  /ui/login/login)

### To reproduce

1. Create an app
2. Don't configure a logout url (redirect url after logout)
3. Login through the app
4. Trigger a logout from the app
5. Click on the "Login" button
6. Get redirected to Consolse, not the App

(you can use the b2b demo application)

### Expected behavior

Instead the login should bring me to the default redirect url. Since my users should login from a client application, it does not make sense to let them log into the console, but send me back to the application.

The button should be labeled "back to the application".

 Another solution would be to provide more information where users will be redirected on the redirect url settings of the application.

### Additional Context

Probably related: The default redirect url of the organization is empty. Expectation here is that it redirects to the custom domain.
I understand the whole flow might not be a bug, but it is confusing.

**Comment by livio-a** [comment] 2024-02-28 06:55
I cannot reproduce. The link above sends me to localhost:3000 if i click on the login button and it also works on my instance.

**Comment by mffap** [comment] 2024-02-28 07:13
> I cannot reproduce. The link above sends me to localhost:3000 if i click on the login button and it also works on my instance.

Changed the default redirect url in the meantime, so that would not work anymore, I guess.
Is there any config that I've missed, like logout url or so?

**Comment by livio-a** [comment] 2024-12-04 08:58
Just stumbled over this again and retested.
If the application does not provide a `post_logout_redirect_uri` on the end_session request, the login UI will redirect the user to the default "logged out" page on the login itself.
The login button on this page will redirect the user to the "default redirect uri".
I'll close this issue, since I can't see any bug.

**Closed by livio-a** 2024-12-04 08:58 UTC
Labels: bug, frontend, auth
