### ISSUE TITLE
Tring to use zitadel actions in web solution with no success.

### ISSUE THREAD

**Issue by vitalybrandes** [zitadel/zitadel#7684] opened 2024-04-01 05:31 UTC
@livio-a 
I will appreciate it if you can check it on your side.
See following:
I setup "permissions" action in action page that include code:
```

function flatRoles(ctx, api) {
  if (ctx.v1.user.grants == undefined || ctx.v1.user.grants.count == 0) {
    return;
  }
  ctx.v1.user.grants.grants.forEach(claim => {
    claim.roles.forEach(role => {
api.v1.claims.setClaim('permission', role)
    })
  })
}
```
![image](https://github.com/zitadel/zitadel/assets/61165619/5d7fb060-3105-459d-8fdc-8bc65b11b4bb)

In my UI side i use this scope:
    _"Scope": "openid permission urn:zitadel:iam:action:permission:log",_

Getting resposne error:
{"error":"server_error","error_description":"Errors.Internal"}

Request URL:
https://1nstance-01-u1bal1.zitadel.cloud/oauth/v2/token
Request Method: POST
Status Code: 500 Internal Server Error

In the Zitadel events page i see following:

Access Token created | 246507009652876239User | 246505807364084063 | zitadel | 1248 | Mon 25. Mar, 12:40:23

{
  "applicationId": "25010635557112079@mobile_spa",
  "audience": [
    "2501063255797112079@mobile_spa",
    "251458844219830674@mobile_spa",
    "250108768566451471"
  ],
  "expiration": "2024-03-25T22:40:23.34924907Z",
  **"scopes": [
    "openid",
    "urn:zitadel:iam:org:project:role:create:mobile",
    "urn:zitadel:iam:org:project:role:delete:mobile",
    "urn:zitadel:iam:org:project:role:manage:mobile",
    "urn:zitadel:iam:org:project:role:readall:mobile",
    "urn:zitadel:iam:org:project:role:read:mobile",
    "urn:zitadel:iam:org:project:role:rent:mobile",
    "urn:zitadel:iam:org:project:role:reserve:mobile",
    "urn:zitadel:iam:org:project:role:return:mobile",
    "urn:zitadel:iam:org:project:role:update:mobile"
  ],**
  "tokenId": "259824084529602823",
  "userAgentId": "256049472551272956"
}

Please please , what i am doing wrong, otherwise is it bug?
Test it for both, Access_token and ID_token creation.

*P.S I am using your saas solution, now on free subscription before purchase.

thanks

_Originally posted by @vitalybrandes in https://github.com/zitadel/zitadel/discussions/7594#discussioncomment-8900702_

**Comment by livio-a** [comment] 2024-04-02 06:20
duplicate of https://github.com/zitadel/zitadel/discussions/7594#discussioncomment-8900702

**Closed by livio-a** 2024-04-02 06:20 UTC

**Comment by vitalybrandes** [comment] 2024-04-04 06:49
Hi, @livio-a  
You close this issue without recommended solution.
While i am trying to use Actions its failed.

Your support appreciated.

**Comment by benr77** [comment] 2024-04-30 06:22
The JS function name has to match with the name of the action. You have named your action "permissions" but the JS function is called "flatRoles".
