### ISSUE TITLE
MFA problem

### ISSUE THREAD

**Issue by kenjkm77** [zitadel/zitadel#7585] opened 2024-03-17 10:49 UTC
Describe the problem
not working MFA adjunted capture with the problem.

![image](https://github.com/zitadel/zitadel/assets/138183207/0bc1c7b9-df26-467d-93f8-755aa098207a)

ERROR MFA netbird

Error with Feature-Policy header: Some features are specified in both Feature-Policy and Permissions-Policy header: payment. Values defined in Permissions-Policy header will be used.

**Comment by hifabienne** [comment] 2024-03-18 08:04
@livio-a @muhlemmer can you help here?

**Comment by kenjkm77** [comment] 2024-03-18 11:14
When I try to activate authentication with the Google Authenticator application, I scan the QR code that appears on the screen and then I enter the code. When I enter it, it does not indicate any message, it only shows that error in the browser console.

**Comment by muhlemmer** [comment] 2024-03-18 11:30
Please submit a [bug report](https://github.com/zitadel/zitadel/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+), not free-form issue, if you are sure it is a bug  on our side and not a mis-configuration. And please provide version info, database details and the "steps to reproduce" steps accordingly.  Because we need to know how you configured zitadel and have an easy way to debug the problem. If you ask me, I don't feel like wasting time on an incomplete issue.

If you you think you might misconfigured something, please open a question in [Q&A discussions](https://github.com/zitadel/zitadel/discussions/categories/q-a), or join the [zitadel discord chat](https://zitadel.com/chat).

**Comment by kenjkm77** [comment] 2024-03-18 11:53
The truth is, if you answer me that you are wasting your time on a bug, I will not continue on this topic, the problem is between you and netbird, I will not waste my time demonstrating errors on third-party platforms, if you feel like it, review between you and netbird @braginini

**Comment by muhlemmer** [comment] 2024-03-18 12:02
All I'm asking is you to give complete information, because what you gave until now gives me nothing workable. If you start with sharing how to (simply) deploy netbird with zitadel, with for example a docker-compose file which starts both of them, it will save a lot of time and you have a higher change of us working on the bug.

We are not netbird users and you cannot expect us to have the knowledge ready to imagine and recreate your issue.

If it is only happening with netbird and not other apps, then it is a configuration specific issue for which you can get help in the community channels I posted above.

**Comment by kenjkm77** [comment] 2024-03-18 13:02
It is a docker-compose image, everything installs itself without us doing anything. When we commented to Netbird, they told us to publish it in the Zitadel thread. It is an installation from 2 days ago, that is, it is the latest version. We tried reinstalling it on another server and the error persists. Netbird indicates it's you I'm just a netbird user

**Comment by fforootd** [comment] 2024-03-18 13:22
> It is a docker-compose image, everything installs itself without us doing anything. When we commented to Netbird, they told us to publish it in the Zitadel thread. It is an installation from 2 days ago, that is, it is the latest version. We tried reinstalling it on another server and the error persists. Netbird indicates it's you I'm just a netbird user

No worries that is fine.

So can you share your browser version and network tab (potentially the post where you see this)?

I just tried and did not see the problem happening to me.

Feel also free to link the comments that were made with netbird.

**Comment by kenjkm77** [comment] 2024-03-18 13:32
Pudiera darte un acceso para que hagas la prueba directamente te gustaria ?

**Comment by fforootd** [comment] 2024-03-18 14:41
> I could give you access to take the test directly, would you like it?

We can do this, you can reach out to me on florian@zitadel.com

**Comment by fforootd** [comment] 2024-04-03 10:37
Please feel free to reopen this issue when you have time.

In the meantime I close it since we lack the data to debug.

**Closed by fforootd** 2024-04-03 10:37 UTC
Labels: waiting, auth
