### ISSUE TITLE
[Bug]: Zitadel CSS/Visual bug on the log-in page

### ISSUE THREAD

**Issue by NicoloLazzaroni** [zitadel/zitadel#8869] opened 2024-11-06 15:16 UTC
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

Latest (dockerized)

### Database

CockroachDB

### Database Version

Latest (dockerized)

### Describe the problem caused by this bug

Hello! I would like to make you aware of a small bug non-English instances have.
In the verification page text goes out of the switch method button
Could this be solved by making the button responsibly fatter? Like becoming bigger toward the bottom of the page.

### To reproduce

1. Set language to Italian (probably also other tho).
2. Set 2FA both via Authenticator and Device-ID.
3. Log-in and on the 2FA page switch 2FA method.

### Screenshots

![Image](https://github.com/user-attachments/assets/3aa6f7f7-d07d-4450-aa5e-3cabf3fe1410)
![Image](https://github.com/user-attachments/assets/b2b7cbd4-2e2c-4c24-850c-136205ec5af0)

### Expected behavior

The button should contain all of the text.

### Operating System

Latest version, dockerized, MacOS.

### Relevant Configuration

N.A.

### Additional Context

N.A.

**Comment by livio-a** [comment] 2024-12-04 08:59
duplicate of #7619 -> i'll close this one

**Closed by livio-a** 2024-12-04 08:59 UTC
Labels: bug, frontend, auth
