### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#2824] opened 2021-12-10 07:02 UTC
We received reports from clients that they get "connection reset by peer" errors when using our APIs.

The error occurred so far at least on:
- Introspection (HTTP)
- ListUserGrants in Management API (gRPC)

**Comment by rmishr** [comment] 2021-12-10 16:28
Thanks @livio-a. At the moment we get this a couple of times a day. If needed I can provide you with some timestamps to search for.

**Comment by livio-a** [comment] 2021-12-13 06:29
Hey @rmishr 
That might be helpful, because we could not yet find out exactly what the problem is.
Do you get the error at one of the endpoints mentioned above, another or is it just random?

**Comment by rmishr** [comment] 2021-12-13 06:52
Hey @livio-a, it has always been the POST request to the instrospection endpoint so far (api.zitadel.ch/oauth/v2/introspect). Last time I see it in our logs is around 2021-12-12 17:39:47.940 CET.

**Comment by fgerschwiler** [comment] 2022-03-04 09:55
Unfortunately we have never been able to reproduce this problem, can you provide us with any further information?

**Comment by rmishr** [comment] 2022-03-07 11:56
Hi @fgerschwiler, we have seen it only sporadically in recent days and we will implement a retry. So from my end you can close it as at this point I do not have any further information I can provide on this issue.

**Comment by fforootd** [comment] 2022-07-26 22:25
I think we can close this ATM since the situation looks calm.

Feel free to reopen.

**Closed by fforootd** 2022-07-26 22:25 UTC
Labels: type: bug, category: backend, state: waiting
