### ISSUE TITLE
Login error "User could not be found" 

### ISSUE THREAD

**Issue by yasukawa426** [zitadel/zitadel#3958] opened 2022-07-13 15:31 UTC
**Describe the bug**
Whenever I try to login through the "other user" option or through another platform (Android, for example), I get the "User could not be found" error. The error goes away if the options "User Loginname must contain orgdomain" and "Validate Org domains" are on. Registration and first login after e-mail confirmation works fine.

**To Reproduce**
1. Disable "User Loginname must contain orgdomain" and "Validate Org domains" on console.
2. Register an user and login in your application.
3. Logout.
4. Try to login using the same user through "Other users" or through another platform.
5. See error "User could not be found"

**Expected behavior**
Be able to register and then login in multiple platforms with the options "User Loginname must contain orgdomain" and "Validate Org domains" disabled.

**Screenshots**
When these options are disabled:
![Opções desativadas](https://user-images.githubusercontent.com/62857460/178769600-1c24bcd1-943d-49e9-9e79-36f7f58a83ed.jpeg)
Get this error with the "Other User" option or through another platform:
User after logout             |  Error with "Other User" option
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/62857460/178768196-8ffa3965-d363-4e5d-af26-d346eef37abc.png) | ![image](https://user-images.githubusercontent.com/62857460/178768672-5f76c620-652c-4fd3-ac34-1f0f18908855.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 103.0.5060.114 (Versão oficial) 64 bits

**Smartphone:**
 - Device: Redmi Note 10
 - OS: Android 11 RKQ1.201022.002. MIUI Global 12.5.5
 - Browser: Chrome
 - Version 103.0.5060.71

Zitadel Version: v2.0.0-v2-alpha.39-amd64

**Comment by hifabienne** [comment] 2022-07-14 06:06
Hi @yasukawa426 
Thanks for your input.
We will have a look at it and get back to you.

**Comment by yasukawa426** [comment] 2022-07-15 13:14
Hi @hifabienne, thanks for the help! 

The way we are setup is we have only one Organization, with the verified domain "stolzlabs.com". Inside the organization we have this user with its username being "yasukawa.luquesi.lucas@gmail.com". However, when these options are disabled, no matter how we write the loginname, we can't log in.


| Domain | Loginname |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62857460/179228338-487293fc-745c-4b0d-b26d-9991983c68ea.png) | ![image](https://user-images.githubusercontent.com/62857460/179229530-5f406ef9-83be-4d7c-b5ad-224dbba0e80a.png) |





| Only username | username@domain (loginname) | something else |
| --- | --- | --- |
| ![Erro](https://user-images.githubusercontent.com/62857460/179226919-45bd8691-b8e2-4aff-bea0-5c475702e41f.jpeg) | ![erro gmail comstolzlabs com](https://user-images.githubusercontent.com/62857460/179226949-c58965c5-75dd-4049-92f1-f1a7fdb24cb8.jpeg) | ![erro stolzlabs com](https://user-images.githubusercontent.com/62857460/179226946-f59a421d-c0e1-48d4-b508-bae7f932232d.png) |

And when the options are enabled, I am able to log in using only the username ("yasukawa.luquesi.lucas@gmail.com").

Is this a bug or am I just understanding something wrong?

Thanks again for the help!

**Comment by hifabienne** [comment] 2022-07-15 13:46
With the loginname show you should be able to login. If this doesn't work its a bug. But I can not reproduce it on my own instance, so I am not sure where the problem is.

Are you running on our SaaS service or have you setup your own instance?
If you have your own instance, can you connect to your DB and have a look at the table projections.users, projections.users_humans, projections.loginnames, and projections.failed_events?

The failed events shows if something went wrong while generating the projections from the events: https://docs.zitadel.com/docs/concepts/eventstore/zitadel#failed-events

In the other tables you should see your users. If the table doesn't show your users something in the projections went wrong.

**Comment by yasukawa426** [comment] 2022-07-15 14:35
We are running our own instance. We'll take a look into the database and then I will get back to you!
Thanks!

**Comment by hifabienne** [comment] 2022-08-15 09:21
Hi @yasukawa426 
Just wanted to ask if you could have a look into this?

**Comment by hifabienne** [comment] 2022-10-25 09:41
@yasukawa426 I will close this issue, because without any more information we will not be able to help.
Feel free to reopen as soon as you provide us some infos.

**Closed by hifabienne** 2022-10-25 09:41 UTC
Labels: type: bug, type: question, lang: go, state: waiting, priority: medium
