### ISSUE TITLE
[Bug]: can't start the registration of TOTP generator

### ISSUE THREAD

**Issue by sp132** [zitadel/zitadel#8207] opened 2024-06-28 06:28 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.4

### Database

CockroachDB

### Database Version

v23.1.8

### Describe the problem caused by this bug

After update from 2.51 to 2.54 [TOTP generator registration](https://zitadel.com/docs/apis/resources/user_service/user-service-register-totp) throws an "mfa_required" error when using a session token obtained via Session resource API.

Multifactor authorization is enforced on org level, both for local and external users.

### To reproduce

1. Disable MFA on existing user or create a new one.
2. Create a session via Session resource API using "user" and "password" checks
3. Using a token from step 2 start TOTP registration process by calling [User Resource API](https://zitadel.com/docs/apis/resources/user_service/user-service-register-totp)
4. Observe an error

### Expected behavior

Call succeeds, response with a pre-shared key is returned

**Comment by muhlemmer** [comment] 2024-07-31 07:29
It works as intended. If ForceMFA is enabled, any API call with a user's (session) token needs to be MFA authenticated. Are you sure that worked in v2.51? Because if it did, that might have been a bug we accidentally fixed in https://github.com/zitadel/zitadel/pull/8069.

If you use the session API for login purposes, the token of the machine user, with sufficient permissions, can be used to update the user's MFA methods.

**Comment by forsak3n** [comment] 2024-08-05 07:45
> It works as intended. If ForceMFA is enabled, any API call with a user's (session) token needs to be MFA authenticated. Are you sure that worked in v2.51?

I'm pretty sure, because we are running two instances (prod and non-prod) of ZITADEL to avoid this kind of problems during the update.

> If you use the session API for login purposes, the token of the machine user, with sufficient permissions, can be used to update the user's MFA methods.

Certainly this is an option, but I would like to avoid doing it. Doing as much self-service with a session token looks nicer in the audit log because the subject will always be a human user performing the action, and not a machine user.

And one can argue that it’s somewhat illogical to require MFA during the TOTP setup process when there is no MFA in place yet.

**Comment by muhlemmer** [comment] 2024-08-14 07:36
@livio-a and I discussed the possibility of ignoring the ForceMFA flag on API methods that add user MFAs, only when the user has no MFA registered. I will prepare a userstory / feature for it later.

**Comment by muhlemmer** [comment] 2024-09-06 14:10
Superseded by https://github.com/zitadel/zitadel/issues/8565

**Closed by muhlemmer** 2024-09-06 14:10 UTC
Labels: bug, auth
