### ISSUE TITLE
[Bug]: Can't add a service user after deleting a service user using the same name. 

### ISSUE THREAD

**Issue by dakshitha** [zitadel/zitadel#5779] opened 2023-05-01 07:13 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/11885043/235421001-26c0d8fd-a963-4b52-a006-c0438247a7f0.png">

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/11885043/235421070-4b21b868-d0b3-458d-9736-824e1123e185.png">

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/11885043/235421130-db13b88a-3f11-472d-9116-32bf76b09437.png">

### To reproduce

Go to service users in a project. 
Delete a service user. 
Add a new service user with the same name. 
When you try to create the user, it says that the user exists.

**Comment by hifabienne** [comment] 2023-05-01 07:23
Hei @dakshitha 
I just tried to reproduce this, but I couldn't for me it works perfectly fine.
Did you still see the user in the overview? After deleting?

**Comment by dakshitha** [comment] 2023-05-01 08:05
No. The user wasn't showing. But I get the message that the user already exists.

**Comment by doncicuto** [comment] 2023-07-09 09:42
Hi @dakshitha and @hifabienne, I've tried to reproduce this issue to try to fix this issue.

If I start a new Zitadel instance with the default org (Zitadel) and try to create a service user, delete it, and add it once again in the same org, there's no problem, the service user is created as expected.

If I create a service user with username test in the default org (Zitadel) and try to create the same service user with username test then I get the "User already exists".

So I guess we  may have two alternatives:

- @hifabienne is this the expected behavior? we can only have one service user with that username throughout all Zitadel orgs or
- @dakshitha could it be that the nextjs username did exist in another org and show the error as Zitadel may require that the username is unique throughout all orgs?

@hifabienne let me know if you want me to change current behavior as a reproducible bug

**Comment by dakshitha** [comment] 2023-07-10 05:29
> Hi @dakshitha and @hifabienne, I've tried to reproduce this issue to try to fix this issue.
> 
> If I start a new Zitadel instance with the default org (Zitadel) and try to create a service user, delete it, and add it once again in the same org, there's no problem, the service user is created as expected.
> 
> If I create a service user with username test in the default org (Zitadel) and try to create the same service user with username test then I get the "User already exists".
Do you mean create another service user in a different org with the  same username as the one in the default org?
> 
> So I guess we may have two alternatives:
> 
> * @hifabienne is this the expected behavior? we can only have one service user with that username throughout all Zitadel orgs or
> * @dakshitha could it be that the nextjs username did exist in another org and show the error as Zitadel may require that the username is unique throughout all orgs?
Yes, this could have been the case. 
> 
> @hifabienne let me know if you want me to change current behavior as a reproducible bug

**Comment by hifabienne** [comment] 2023-07-10 05:51
Hei @doncicuto 
Yes that is intended. Usernames have to be unique across all organizations.
This is for human as well as for service users.

**Comment by hifabienne** [comment] 2024-01-15 12:18
I will close this issue for now, as I can't reproduce.
Feel free to reopen when it appears again

**Closed by hifabienne** 2024-01-15 12:18 UTC
Labels: bug
