### ISSUE TITLE
[Bug]: Getting 'token was not issued for this client' when revoking an UI token from backend

### ISSUE THREAD

**Issue by oscarcalderonc** [zitadel/zitadel#7117] opened 2023-12-29 13:38 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.2

### Database

PostgreSQL

### Database Version

14

### Describe the problem caused by this bug

I am currently experiencing an issue when trying to revoke a token. Here's an example request where I am getting the issue "token was not issued for this client":

```
curl --request POST \
  --url https://my.zitadelinstance.com/oauth/v2/revoke \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --header 'User-Agent: insomnia/8.5.1' \
  --cookie __Secure-zitadel.useragent=MTcwMzg1NjMyNXxOUkE0YTlaRWpuZGRza1N6d21YRXN1ZDU3aUZWSzV2WHJWeWFzUTlDd0d3TjAwSWI3QlV2WGZMd1ZZVEJqWml4c0VBajZBVmMzLTB2NmdiWTJ1RHNZbjN4MU5pZGctND18v96TZ7Z-IRdwVhDXBc0LGF7sLoRm4ClFbklL9EWO5dY%3D \
  --data client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer \
  --data client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjI0NTgwNDMxOTg4NDk2ODA1OSJ9.eyJpc3MiOiIyNDU4MDQzMDI3NTU0OTYwNTlAYXR0ZW50aW9uLWRldiIsInN1YiI6IjI0NTgwNDMwMjc1NTQ5NjA1OUBhdHRlbnRpb24tZGV2IiwiYXVkIjpbImh0dHBz... \
  --data token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjI0NzIwNTAzMDk0MjIxMjMyNCJ9.eyJhdWQiOlsiMjQ1ODA0MjY3MjU0OTA3MDAzQGF0dGVudGlvb...
```

The access token was generated by an User-Agent application, and I'm trying to revoke the token from the backend, which uses a json key from an API application. If I inspect the access token, I can see it contains both the API client id as well as the User-Agent client id as part of the audience:

```
{
  "aud": [
    "245804267254907003@my-project", // user agent app
    "245804302755496059@my-project", // api app
    "245804230982500475"
  ],
...
```

According to this thread in discord (https://discord.com/channels/927474939156643850/1074648759893512292/1078198658954170544) I understood it would be possible to revoke this token from my API application, as the client ID of the API is part of the audience of the token, and it references this issue: https://github.com/zitadel/zitadel/issues/5276

Which seems to have some changes merged, but not sure if this is still a work in progress.

### To reproduce

- Create an User Agent application
- Create an API application
- Configure your frontend to use the User Agent details, and use something like oidc-client-ts to generate access tokens
- Send the access token to the backend
- The backend has the details of the JSON key generated for the API application
- Generate a client assertion using zitadel tools with the following command: `zitadel-tools key2jwt --audience=https://my.zitadelinstance.com --key=my-file.json`
- The backend tries to revoke the token using this request:
```
curl --request POST \
  --url https://my.zitadelinstance.com/oauth/v2/revoke \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --header 'User-Agent: insomnia/8.5.1' \
  --cookie __Secure-zitadel.useragent=MTcwMzg1NjMyNXxOUkE0YTlaRWpuZGRza1N6d21YRXN1ZDU3aUZWSzV2WHJWeWFzUTlDd0d3TjAwSWI3QlV2WGZMd1ZZVEJqWml4c0VBajZBVmMzLTB2NmdiWTJ1RHNZbjN4MU5pZGctND18v96TZ7Z-IRdwVhDXBc0LGF7sLoRm4ClFbklL9EWO5dY%3D \
  --data client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer \
  --data client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjI0NTgwNDMxOTg4NDk2ODA1OSJ9.eyJpc3MiOiIyNDU4MDQzMDI3NTU0OTYwNTlAYXR0ZW50aW9uLWRldiIsInN1YiI6IjI0NTgwNDMwMjc1NTQ5NjA1OUBhdHRlbnRpb24tZGV2IiwiYXVkIjpbImh0dHBz... \
  --data token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjI0NzIwNTAzMDk0MjIxMjMyNCJ9.eyJhdWQiOlsiMjQ1ODA0MjY3MjU0OTA3MDAzQGF0dGVudGlvb...
```
- Obtain the following response:
```
{
	"error": "invalid_client",
	"error_description": "token was not issued for this client"
}
```

### Screenshots

This is the User Agent application configuration:
<img width="977" alt="image" src="https://github.com/zitadel/zitadel/assets/70549595/8d99c31d-f162-442c-9c63-b7ec80fba639">
<img width="850" alt="image" src="https://github.com/zitadel/zitadel/assets/70549595/833dad73-17d0-4a46-ac8b-8df73de29228">

### Expected behavior

To get the token revoked, as the token audience contains both the client ids of the API and User Agent applications

**Comment by hifabienne** [comment] 2024-01-02 09:58
hei @muhlemmer @livio-a can you help here?

**Comment by muhlemmer** [comment] 2024-01-05 09:15
As the linked issue #5276 is not merged yet, no you cannot expect it to work. Currently you can only revoke from the client that obtained the token.

What was further discussed in that thread (and that works) is introspection from trusted audience.

Closing as invalid (not a bug) and duplicate of the feature request.

**Closed by muhlemmer** 2024-01-05 09:15 UTC
Labels: bug
