### ISSUE TITLE
Unable to start zitadel using example

### ISSUE THREAD

**Issue by Dima-Kal** [zitadel/zitadel#4610] opened 2022-10-25 15:14 UTC
**Describe the bug**
When container is started the following issue appears and the container is constantly restarting:

```
time="2022-10-25T15:10:45Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-10-25T15:10:45Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2022-10-25T15:10:45Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-10-25T15:10:45Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2022-10-25T15:10:45Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-10-25T15:10:47Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-25T15:10:47Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:45" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:47Z" level=fatal msg="unable to migrate step 3" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:98" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:54Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-10-25T15:10:54Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2022-10-25T15:10:54Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-10-25T15:10:54Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2022-10-25T15:10:54Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-10-25T15:10:56Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-25T15:10:57Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:45" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:57Z" level=fatal msg="unable to migrate step 3" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:98" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
```

**To Reproduce**
Used the example here:
https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example

**Comment by hifabienne** [comment] 2022-10-26 06:16
Hi @Dima-Kal 
The error message tells that the PasswordComplexityPolicy defines that a password should contain an upper letter.
Do you have an upper letter in the password of your first admin user?

**Comment by Dima-Kal** [comment] 2022-10-26 06:41
> Hi @Dima-Kal The error message tells that the PasswordComplexityPolicy defines that a password should contain an upper letter. Do you have an upper letter in the password of your first admin user?

yes, tried it with "Secret_DB_User_Password"
and then changed it to:
```
    User:
      # If the user doesn't exist already, it is created
      Username: 'zitadel_user'
      Password: 'f#AfFd7y783ho'
    Admin:
      Username: 'root'
      Password: '!ws#4dD3qss'
```

**Comment by hifabienne** [comment] 2022-10-26 06:47
Hei @Dima-Kal 
This message is not about your DB-User.
It is about your first user in your ZITADEL instance that has admin rights.
It should be in the FirstInstance

**Comment by Dima-Kal** [comment] 2022-10-26 07:00
> Hei @Dima-Kal This message is not about your DB-User. It is about your first user in your ZITADEL instance that has admin rights. It should be in the FirstInstance

Ok that indeed solved it, I had another issue:

```
time="2022-10-26T06:58:00Z" level=fatal msg="unable to initialize ZITADEL" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:68" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=zitadel-db port=26257 user=zitadel_user dbname=zitadel application_name=zitadel sslmode=verify-full dbname=zitadel password=xxxxx sslrootcert=/crdb-certs/ca.crt sslcert=/crdb-certs/client.zitadel_user.crt sslkey=/crdb-certs/client.zitadel_user.key`: failed to configure TLS (unable to read cert: open /crdb-certs/client.zitadel_user.crt: no such file or directory))"
```

"solved" it by removing 'Cert' and 'Key' from this configuration
Database:
  cockroach:
    Host: 'zitadel-db'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
       # Cert: "/crdb-certs/client.zitadel_user.crt"
       # Key: "/crdb-certs/client.zitadel_user.key"

**Comment by hifabienne** [comment] 2022-10-26 07:22
I will close the issue since we have found the problem

**Comment by Dima-Kal** [comment] 2022-10-26 07:24
> I will close the issue since we have found the problem

Should i open a new issue regarding this?

```
Ok that indeed solved it, I had another issue:

time="2022-10-26T06:58:00Z" level=fatal msg="unable to initialize ZITADEL" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:68" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=zitadel-db port=26257 user=zitadel_user dbname=zitadel application_name=zitadel sslmode=verify-full dbname=zitadel password=xxxxx sslrootcert=/crdb-certs/ca.crt sslcert=/crdb-certs/client.zitadel_user.crt sslkey=/crdb-certs/client.zitadel_user.key`: failed to configure TLS (unable to read cert: open /crdb-certs/client.zitadel_user.crt: no such file or directory))"
"solved" it by removing 'Cert' and 'Key' from this configuration

Database:
  cockroach:
    Host: 'zitadel-db'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
       # Cert: "/crdb-certs/client.zitadel_user.crt"
       # Key: "/crdb-certs/client.zitadel_user.key"
       
```

**Comment by hifabienne** [comment] 2022-10-26 08:25
@Dima-Kal

**Comment by Dima-Kal** [comment] 2022-10-26 08:27
> @Dima-Kal Did you use a cockroach Cloud? They do everything with the root cert and you do not need the cert and key

I've used the example here https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example
here's my compose:

```
  zitadel:
    container_name: "zitadel"
    restart: "always"
    networks:
      - "docker_network"
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "8A960501A73B30FC5F33E2160E25B91A" --tlsMode external'
    volumes:
      - "./configs/zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./configs/zitadel/zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./configs/zitadel/zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/zitadel-certs:/crdb-certs:ro"
    depends_on:
      chown:
        condition: "service_completed_successfully"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.${SERVER_DOMAIN}`)"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
    ports:
      - "47983:8080"

  chown:
    image: "cockroachdb/cockroach:v22.1.0"
    networks:
      - "docker_network"
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "cp /certs/ca.crt /zitadel-certs/ && cp /certs/client.root.crt /zitadel-certs/ && cp /certs/client.root.key /zitadel-certs/ && chown 1000:1000 /zitadel-certs/* && chmod 0400 /zitadel-certs/*",
      ]
    volumes:
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/certs:/certs:ro"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/zitadel-certs:/zitadel-certs:rw"
    depends_on:
      zitadel-db:
        condition: "service_healthy"

  zitadel-db:
    container_name: "zitadel-db"
    restart: "always"
    networks:
      - "docker_network"
    volumes:
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/certs:/cockroach/certs:rw"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/data:/cockroach/cockroach-data:rw"
    image: "cockroachdb/cockroach:v22.1.3"
    command: "start-single-node --advertise-addr zitadel-db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    #ports:
    #  - "9090:8080"
    #  - "26257:26257"
```

**Comment by hifabienne** [comment] 2022-10-26 09:03
We will have a look at it

**Comment by eliobischof** [comment] 2022-10-26 09:13
I can reproduce the issue and am working on a fix.

**Closed** 2022-10-26 11:34 UTC
Labels: type: bug, category: docs, state: in progress, effort: 1

**Comment by eliobischof** [comment] 2022-10-26 11:39
@Dima-Kal the files zitadel-secret-config.yam amd docker-compose.yaml in the example is fixed. Can you please download these files as described in the docs and try again?

**Comment by Dima-Kal** [comment] 2022-10-26 11:52
> @Dima-Kal the files example-zitadel-secrets.yaml amd docker-compose.yaml in the example is fixed. Can you please download these files as described in the docs and try again?

Hey @eliobischof  look like its starting now:
```
time="2022-10-26T11:46:27Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-10-26T11:46:27Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2022-10-26T11:46:27Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-10-26T11:46:27Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2022-10-26T11:46:27Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-10-26T11:46:28Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-10-26T11:46:28Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-26T11:46:28Z" level=info msg="starting migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-26T11:46:29Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-26T11:46:29Z" level=info msg="starting migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-26T11:46:29Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-26T11:46:29Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-26T11:46:32Z" level=info msg="verify migration 04_eventstore_indexes" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-26T11:46:32Z" level=info msg="starting migration 04_eventstore_indexes" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-26T11:46:34Z" level=info msg="verify migration config_change" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-26T11:46:34Z" level=info msg="starting migration config_change" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-26T11:46:47Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:63" lockerID=185033915268857904 workers=1
time="2022-10-26T11:46:47Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:63" lockerID=185033915285635120 workers=1
time="2022-10-26T11:46:48Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:255"
```

but when trying to access https://192.168.100.100:47983/ (local server ip address, 47983 mapped to 8080) and its not reaching web interface

**Comment by eliobischof** [comment] 2022-10-26 12:09
ZITADEL is listening on :8080, but with the example, you have a traefik proxy in between that listens on :443.

Also, ZITADEL maps the [virtual instance](https://docs.zitadel.com/docs/concepts/structure/instance#multiple-virtual-instances) using the requests host header. In the example, that's my.domain.

See https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example
![image](https://user-images.githubusercontent.com/12727842/198021591-fc8269de-2ee3-4564-a6d9-ce9c2b4c2193.png)

BTW, I just see a typo in the screenshot :smile: *127.0.1.1* should be *127.0.0.1*

**Comment by Dima-Kal** [comment] 2022-10-26 12:15
@eliobischof I dont have a rules file for traefik, can you give an example what to configure via labels?

**Comment by eliobischof** [comment] 2022-10-26 12:24
I think you don't need to adjust the example traefik config.
![image](https://user-images.githubusercontent.com/12727842/198024298-25ec74ac-918e-407d-8220-92e9ef317eb6.png)

I guess *192.168.100.100* is a virtual machine? I think all you need to do is to map the VM port *47983* to *443*, configure *ExternalPort* in *example-zitadel-config.yaml* to *47983* and add the line *192.168.100.100 my.domain* to your */etc/hosts* file.

**Comment by eliobischof** [comment] 2022-10-26 14:59
Your traffic goes first to the Traefik proxy which is listening at :443, from there it goes to zitadel over the docker network. You can see this in the Traefik config:
![image](https://user-images.githubusercontent.com/12727842/198061563-4cfa5972-c037-4adc-9cbf-62ec8b6b41e5.png)

What is your current error?

**Comment by Dima-Kal** [comment] 2022-10-26 15:07
@eliobischof 
traefik reports the following issue:
```
time="2022-10-26T15:05:40Z" level=error msg="service \"zitadel\" error: port is missing" providerName=docker container=zitadel-authentication-45f9eed1df38da755a6d2b6df2fea307c66d782485e1437bb55147fcf8507e55
```

these are the labels i've configured:
```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.zitadel.entrypoints=websecure"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.url=h2c://zitadel:8080"
```

**Comment by eliobischof** [comment] 2022-10-26 15:17
What happens if you take the exact example files like described in the [docs page](https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example) and just do the steps I described [above](https://github.com/zitadel/zitadel/issues/4610#issuecomment-1291954078)? 

Because in the compose file [you posted above](https://github.com/zitadel/zitadel/issues/4610#issuecomment-1291676975), you don't have a Traefik service at all.

**Comment by Dima-Kal** [comment] 2022-10-26 15:47
another issue, if trying to start compose stack again, the chown container fails:

```
2022-10-26 17:47:56	
authentication-certs-1
failed to generate client certificate and key: error writing client certificate to /zitadel-certs/client.zitadel_user.crt: open /zitadel-certs/client.zitadel_user.crt: file exists
```
needed to disable certs container and dependency in zitadel

**Comment by eliobischof** [comment] 2022-10-31 08:17
> @eliobischof traefik reports the following issue:
> 
> ```
> time="2022-10-26T15:05:40Z" level=error msg="service \"zitadel\" error: port is missing" providerName=docker container=zitadel-authentication-45f9eed1df38da755a6d2b6df2fea307c66d782485e1437bb55147fcf8507e55
> ```
> 
> these are the labels i've configured:
> 
> ```
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.zitadel.rule=Host(`zitadel.${SERVER_DOMAIN}`)"
>       - "traefik.http.routers.zitadel.entrypoints=websecure"
>       - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
>       - "traefik.http.services.zitadel.loadbalancer.server.url=h2c://zitadel:8080"
> ```

Can you configure the port using a label, as described [here](https://doc.traefik.io/traefik/providers/docker/#port-detection)?

**Comment by eliobischof** [comment] 2022-10-31 08:32
> another issue, if trying to start compose stack again, the chown container fails:
> 
> ```
> 2022-10-26 17:47:56	
> authentication-certs-1
> failed to generate client certificate and key: error writing client certificate to /zitadel-certs/client.zitadel_user.crt: open /zitadel-certs/client.zitadel_user.crt: file exists
> ```
> 
> needed to disable certs container and dependency in zitadel

Good catch.
Created a PR that fixes this https://github.com/zitadel/zitadel/pull/4640

**Comment by Dima-Kal** [comment] 2022-11-02 17:37
> > @eliobischof traefik reports the following issue:
> > ```
> > time="2022-10-26T15:05:40Z" level=error msg="service \"zitadel\" error: port is missing" providerName=docker container=zitadel-authentication-45f9eed1df38da755a6d2b6df2fea307c66d782485e1437bb55147fcf8507e55
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > these are the labels i've configured:
> > ```
> >     labels:
> >       - "traefik.enable=true"
> >       - "traefik.http.routers.zitadel.rule=Host(`zitadel.${SERVER_DOMAIN}`)"
> >       - "traefik.http.routers.zitadel.entrypoints=websecure"
> >       - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
> >       - "traefik.http.services.zitadel.loadbalancer.server.url=h2c://zitadel:8080"
> > ```
> 
> Can you configure the port using a label, as described [here](https://doc.traefik.io/traefik/providers/docker/#port-detection)?

added 
```
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
```
did not work
