### ISSUE TITLE
[Bug]: Web UI throws error when a user has no Memberships

### ISSUE THREAD

**Issue by lusu007** [zitadel/zitadel#7368] opened 2024-02-11 15:50 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.44.2

### Database

PostgreSQL

### Database Version

16.1

### Describe the problem caused by this bug

The Web UI throws an error in the browser's console if a newly registered user does not have any Memberships.

```
main.9d8154a9d7207c55.js:1  Error: No organizations found!
    at main.9d8154a9d7207c55.js:1:312288
    at Generator.next (<anonymous>)
    at i (main.9d8154a9d7207c55.js:1:6846117)
    at p (main.9d8154a9d7207c55.js:1:6846319)
    at v.invoke (polyfills.fd4735676522f440.js:1:6553)
    at Object.onInvoke (main.9d8154a9d7207c55.js:1:6196801)
    at v.invoke (polyfills.fd4735676522f440.js:1:6493)
    at M.run (polyfills.fd4735676522f440.js:1:1919)
    at polyfills.fd4735676522f440.js:1:16763
    at v.invokeTask (polyfills.fd4735676522f440.js:1:7171)
```

### To reproduce

1. Register a new user
2. Login to the user's management page
3. Open the browser console and see the error

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/10341994/c2523c3a-6d22-4b7b-95b2-449cf46a657b)

### Operating System

OS: Windows 11
Browser: Microsoft Edge Version 122.0.2365.16

**Comment by livio-a** [comment] 2024-02-12 09:41
@lusu007 thanks for raising this. We'll check how to fix this.

**Comment by stebenz** [comment] 2024-12-12 14:28
@lusu007 to quickly check in here, there were several optimizations since this issue were created, could you check if this problem still occurs?
I tried it several ways to reproduce, without much success.
As I currently see it, it could occur with the expected eventual consistency of the membership.

I will close this issue for now, could you please reopen it if it still persists and add maybe some additional details on how you register the user and the exact steps to reproduce?

**Closed by stebenz** 2024-12-12 14:28 UTC
Labels: bug, good first issue, resources

**Comment by lusu007** [comment] 2024-12-13 01:53
It seems to be fixed! Thank you 😊
