### ISSUE TITLE
[Bug]: Terminate an existing session can be called more than once without an error

### ISSUE THREAD

**Issue by ashep** [zitadel/zitadel#8067] opened 2024-06-04 06:40 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.52

### Database

PostgreSQL

### Describe the problem caused by this bug

Serially called [session termination method](https://zitadel.com/docs/apis/resources/session_service/session-service-delete-session) returns no error.

### To reproduce

1. Create a user session.
2. Call the [session termination method](https://zitadel.com/docs/apis/resources/session_service/session-service-delete-session).
3. Get no error, which is expected because it is an existing session.
4. Call the session termination method again.
5. Get no error, which is unexpected because the session is already finished.

### Expected behavior

Receive an error when trying to finish an already finished session.

**Comment by hifabienne** [comment] 2024-06-10 13:01
Hi @ashep 
I do believe that this is currently as expected and not a bug.
The intention behind this is, that if you send mulitple times a temination request the result is always the same --> a terminated session 
It is basically an update of the session object without a change.

In older api versions we used to return an error if we got an update object request and nothing has changed. This led to some problems and was mostly unexpected behaviour for users of our APIs, and we decided to change that behaviour for our new apis.

@eliobischof @stebenz @livio-a  please correct me if what I stated above is wrong

**Comment by livio-a** [comment] 2024-06-10 14:14
> Hi @ashep I do believe that this is currently as expected and not a bug. The intention behind this is, that if you send mulitple times a temination request the result is always the same --> a terminated session It is basically an update of the session object without a change.
> 
> In older api versions we used to return an error if we got an update object request and nothing has changed. This led to some problems and was mostly unexpected behaviour for users of our APIs, and we decided to change that behaviour for our new apis.
> 
> @eliobischof @stebenz @livio-a please correct me if what I stated above is wrong

I can confirm that this is indeed intended like that.

If think for future APIs the was a discussion if this should only apply to updates (POST/PUT/PATCH) and not to deletes. @eliobischof , correct?

**Comment by ashep** [comment] 2024-06-10 14:38
@hifabienne @livio-a got it. Thank you for your responses 🙏

**Comment by hifabienne** [comment] 2024-06-11 07:08
I will close the issue because it works as expected

**Closed by hifabienne** 2024-06-11 07:08 UTC
Labels: bug, auth, resources
