### ISSUE TITLE
Azure AD Identity Brokering forces user to create password

### ISSUE THREAD

**Issue by fabius** [zitadel/zitadel#4472] opened 2022-09-29 14:55 UTC
**Describe the bug**
When using an Azure AD Identity Broker, a user has to provide a password

**To Reproduce**
1. Register a new user using an OIDC connection to your Azure AD application.
2. Click the link in the E-Mail to finish the account initialization
3. Enter your information
4. **Enter a password**

**Expected behavior**
User information should be automatically fetched && no additional password should be necessary.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: v1.44.101

**Additional context**
Since OIDC works just fine with Google, I expect this to be related to #2973

**Comment by hifabienne** [comment] 2022-10-13 13:57
Hi @fabius 

Sorry for the late reply. 
We do have some problems with the AzureAD as identity provider. 
At the moment we use all the properties that are returned from the provider and create the user in ZITADEL.
Unfortunately the email_verified property is not set, because this is required in ZITADEL at the moment the user will get an initialization mail.
We are currently on the topic of having templates for identity providers where you could configure things like this.
#4431

**Comment by hifabienne** [comment] 2022-10-18 06:20
Hi @fabius 

We found out what the problem is, thanks to this issue: #4570 
The problem is if you do not have a session. We will fix this asap.
But with the azureAD you will probably have some more issues. That will be resolved with the IDP Templates

**Comment by mffap** [comment] 2022-11-22 10:23
@hifabienne is this resolved with the new guide?
https://docs.zitadel.com/docs/guides/integrate/azuread-oidc

**Closed** 2022-11-22 10:39 UTC
Labels: type: bug, category: backend, state: in progress
