### ISSUE TITLE
Error Page on Login attempt

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4164] opened 2022-08-11 06:41 UTC
As an end user I never want to see a page in the login where I can't do anything after, at least I need to be able to restart the whole login again

Acceptance Criteria:
- [ ] End user never sees internal error page
- [ ] If internal error page has to be shown I want to be able to click login and start the whole login process
- [ ] The error page tells me what I should do next

**Additional Context**

Wenn I try to login with the (inactive) user Grüj Idlanir, it shows the following error page.

![Image](https://user-images.githubusercontent.com/48990649/184077805-1a9199dd-230b-4d29-aaf8-3057d6ae8497.png)

![Image](https://user-images.githubusercontent.com/48990649/184077720-74995fb2-d08d-49af-8aa9-af59ef415618.png)

expected behavior: it shouldn't show an error message in the first place. I expect to get to the auth prompt (password/pwdless). Second the error should be more 'readible' for the user and offer them a way to get around it or at the bare minimum a way back to the login page.

**Comment by hifabienne** [comment] 2022-08-15 11:56
Hei @juergrinaldi I could not reproduce this one.
The error message normally says that you did not start the login from an application and therefore you do not have an authrequest. Without the authrequest we are not able to login you users.
To which application did you try to login.

Possible would be that you opened the same authrequest in 2 tabs. One got closed and then you have this problem.

**Comment by juergrinaldi** [comment] 2022-08-15 12:51
@hifabienne I couldn't reproduce this error anymore neither.

I just tried to login to the test org you see above (https://testyface-rmkmkz.zitadel.cloud/) via browser (chrome). I'm not sure if I had two authrequests at the same time.

But my second statement that the error message should have better 'readability' and having a fallback (i.e. button back to the login page) still stands. this is true for all error messages and other -  seemingly - "dead ends".

**Comment by mffap** [comment] 2022-09-01 07:59
I could reproduce this one. See video below. When you setup OTP and click on the <- button on top, then this error pops-up. There exists a workaround by going back in the browser history. This is obviously not very intuitive.

https://user-images.githubusercontent.com/1366906/187862275-db83bfc1-baf2-43e4-a692-a8a4b7a5f646.mp4

**Comment by hifabienne** [comment] 2024-05-01 08:51
I rechecked this and the back buttons are correctly implemented now. 
Will close the issue

**Closed by hifabienne** 2024-05-01 08:51 UTC
Labels: frontend
