### ISSUE TITLE
Redirect URI deletion doesn't work

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4204] opened 2022-08-16 15:49 UTC
**Describe the bug**
When deleting a redirect URI, the operation succeeds, but after refreshing the URI is still there.

**To Reproduce**
1. Create application
```tf
resource "zitadel_org" "org" {
  name = "org"
}

resource "zitadel_project" "project" {
  depends_on = [zitadel_org.org]

  org_id = zitadel_org.org.id

  name                     = "project"
  project_role_assertion   = "true"
  project_role_check       = "true"
  has_project_check        = "true"
  private_labeling_setting = "PRIVATE_LABELING_SETTING_UNSPECIFIED"
}

resource "zitadel_application_oidc" "application_oidc" {
  depends_on = [zitadel_org.org, zitadel_project.project]

  project_id = zitadel_project.project.id
  org_id     = zitadel_org.org.id

  name                        = "webapp"
  redirect_uris               = ["http://localhost:8080"] // <<<
  response_types              = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types                 = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE", "OIDC_GRANT_TYPE_REFRESH_TOKEN"]
  post_logout_redirect_uris   = ["http://localhost:8080"]
  app_type                    = "OIDC_APP_TYPE_WEB"
  auth_method_type            = "OIDC_AUTH_METHOD_TYPE_NONE"
  version                     = "OIDC_VERSION_1_0"
  clock_skew                  = "0s"
  dev_mode                    = "true"
  access_token_type           = "OIDC_TOKEN_TYPE_BEARER"
  access_token_role_assertion = "false"
  id_token_role_assertion     = "true"
  id_token_userinfo_assertion = "true"
  additional_origins          = []
}
```
2. Delete a redirect URI
3. Save
4. Refresh

**Screenshots**
![Screenshot 2022-08-16 at 17 42 31](https://user-images.githubusercontent.com/58290976/184921747-da5c4905-f9af-4d16-a417-fadc3cb9b209.png)
![Screenshot 2022-08-16 at 17 43 21](https://user-images.githubusercontent.com/58290976/184921872-fce5fbea-d8e3-4626-bfc8-9d1dc0258765.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5
 - Browser: Safari

**Additional context**
Observed on ZITADEL Cloud 2.1.0

**Comment by DavideWalder** [comment] 2022-08-16 15:56
The same goes for Post Logout URIs

**Comment by livio-a** [comment] 2022-08-17 05:18
Hey @DavideWalder 

Thanks for reporting this. I could reproduce it and we will look into it shortly.

**Comment by hifabienne** [comment] 2023-01-03 12:33
I have created the corresponding user story for this bug. It is low in priority, since you normaly should not have no redirect urls. Please subscribe to the following issue if you want to get updates, we will close this one.
https://github.com/zitadel/zitadel/issues/4971

**Closed by hifabienne** 2023-01-03 12:33 UTC
Labels: type: bug, category: backend

**Comment by s0l4r** [comment] 2024-03-18 10:50
FYI. You also cannot edit (by removing and adding a new) post logout redirect URL once added.
