### ISSUE TITLE
Improvement/QoL: Guide Browser to select the correct username for password saving

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4196] opened 2022-08-16 08:29 UTC
Currently the browser selects the initialization code as the username for password saving.

Can we somehow 'guide' the browser to take the actual username? and if not - or if we don't want this because of security reasons - can we surpress the password saving alltogether?

![image](https://user-images.githubusercontent.com/48990649/184833789-6b160c9b-a17c-47c1-9b43-b6b4bbe557ec.png)

**Comment by fforootd** [comment] 2022-08-30 13:54
duplicate of https://github.com/zitadel/zitadel/issues/2740

**Closed by fforootd** 2022-08-30 13:54 UTC
Labels: category: frontend, priority: low, state: triage
