### ISSUE TITLE
Redirect URI not working

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4543] opened 2022-10-12 13:01 UTC
**Describe the bug**
After entering the password, the user is redirected back to the login page (as if nothing happened), instead of the proper redirect URI. This is solved by removing the default login URI on the organization. The odd thing is that readding the default redirect URI on the organization doesn't reintroduce the bug.

It seems like deleting and readding the default redirect URI on the organization changes some other state. The same happens if I initialize the organization without a default redirect (if add one and then remove it it works).

I can't provide the Terraform spec to reproduce since i also involves instance configurations (not available yet), but happy to provide more details if needed.

This used to work with previous versions, it might be tied to a recent release.

The redirect URI is also set on the instance

**Additional context**
ZITADEL Cloud 2.8.0

**Comment by hifabienne** [comment] 2022-10-12 16:03
@DavideWalder Thanks for your report.

I could not reproduce your issue, but maybe I do not have the same entry point or configuration. So can you please answer the following questions?

Did you add a default redirect url, if yes on an instance or on an org? Or should it just redirect to a url you are sending with your authorization request?
How do you get to the ZITADEL login? Org which url do you open?

Maybe you can send us a har file so we have some more information about what happens?

**Comment by DavideWalder** [comment] 2022-10-14 06:38
1. I added a default URI to the instance
2. Create a new organization (using the instance defaults, no overriding)
3. Invited a user to that organization
4. I'll send you a HAR file on Discord with what the user did

Notes:
- The invitation flow doesn't seem to be responsible, this happens even with logins (see the last bit of the HAR export)
- The frontend is correctly passing the redirect URI

**Comment by DavideWalder** [comment] 2022-10-14 06:43
Instance settings
![Screenshot 2022-10-14 at 08 40 31](https://user-images.githubusercontent.com/58290976/195779551-8236940c-91bf-43b1-8fa4-e4287ebaebbb.png)

**Comment by DavideWalder** [comment] 2022-10-14 06:46
Minimal steps to fix the issue:
- remove redirect URI from organizations settings
- Reset settings to instance default

**Comment by DavideWalder** [comment] 2022-10-14 17:31
From a quick look at the code, it looks like if there is no login policy on the organzation (as would be if someone resets it to the instance settings), the default redirect URI is not the one of the instance but `""`:
https://github.com/zitadel/zitadel/blob/fbd04d399d8b71cdfc69d1634f6c6f31cbc6b7ab/internal/api/ui/login/policy_handler.go#L25
https://github.com/zitadel/zitadel/blob/bffb10a4b4a854b00b04bfe030bd74a3c07cb830/internal/query/login_policy.go#L329

**Comment by hifabienne** [comment] 2022-10-18 06:41
@DavideWalder Sorry maybe I do not understand you correctly.
You said that you do not set/overwrite the instance settings on your organization.
But to fix it you did remove the uri from the organization settings. This tells me that you did set a default redirect url?

The other thing that is unclear to me is, that this happens with applications not in dev mode. So the default redirect url does not have anything to do with your application settings.

The default use case is, that you redirect from an application to ZITADEL with an authorization request. The authorization request has a redirect url, that must be configured on your application.

The default redirect url does only trigger if we do not have an authorization request. e.g when the user comes from an email eg. password reset, initial mail, etc.

The code line you did mention is only the initialization. Some lines later we fill the urls:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/38692350/196354859-63157c56-67c7-4150-a56a-59f09caa55b9.png">

**Comment by DavideWalder** [comment] 2022-10-18 06:49
@hifabienne I did set a default redirect URI on the instance, and I'm setting the redirect URI in the authorization request.
I managed to reliably reproduce the bug on all the instances, the application settings don't play any role indeed.

1. Set a default URI on the instance
2. Create an organization (without changing the login policy)
3. Create a user in that organization
4. The user will be able to set their password and will be sent to the login page afterwards, but won't be able to login (after the login it will be sent back to the login page, as if nothing happened)
5. Click on "Save" in the login policy settings of the organization
6. Now everything works

**Comment by DavideWalder** [comment] 2022-10-18 06:56
> @DavideWalder Sorry maybe I do not understand you correctly. You said that you do not set/overwrite the instance settings on your organization. But to fix it you did remove the uri from the organization settings. This tells me that you did set a default redirect url?
> 
> The other thing that is unclear to me is, that this happens with applications not in dev mode. So the default redirect url does not have anything to do with your application settings.
> 
> The default use case is, that you redirect from an application to ZITADEL with an authorization request. The authorization request has a redirect url, that must be configured on your application.
> 
> The default redirect url does only trigger if we do not have an authorization request. e.g when the user comes from an email eg. password reset, initial mail, etc.
> 
> The code line you did mention is only the initialization. Some lines later we fill the urls: <img alt="image" width="588" src="https://user-images.githubusercontent.com/38692350/196354859-63157c56-67c7-4150-a56a-59f09caa55b9.png">

What I meant with the lines of code I referenced, is that if there is no login policy on the organization, the query doesn't return any row (`rows.Next()` doesn't return anything), so `defaultRedirectURI` will stay an empty string, instead of defaulting to the instance default redirect URI.

**Comment by DavideWalder** [comment] 2022-10-18 07:05
The weird thing is that the `GetLoginPolicy` endpoint correctly returns the instance default (so if no login policy is set on the organization, it returns the instance settings)

**Comment by hifabienne** [comment] 2022-10-18 07:17
Unfortunately I cant reproduce your problem.
I did the following:
1. Set default redirect url on my instance to zitadel.com
2. create an organization without changing the policy
3. create a user in the organization
4. Click initialize user in the email --> password set screen, click next, redirect to zitadel.com

Because I redirect to our website I will not be redirected back to our login with a proper authorization request. 

But in your case the user should be redirected to your application, because you do not have an active token you should be redirected back to ZITADEL login, where the you should enter your login data.

The policy is always read either from the organization or from the instance in total. we do not read the policy from the oganization and fill the redirect url from the instance. In your case because no organization setting is existing we will read the complete policy from the instance.

**Comment by hifabienne** [comment] 2022-10-18 07:26
The goal of the redirect url is to send you somewhere, from where you can start an authorize request. Because without the authorize request, we cant make the login.

I am not sure if your problem is the redirect url. as i can see from the har file. it looks like you have been redirected and then get back to zitadel login ui

**Comment by DavideWalder** [comment] 2022-10-18 07:32
Mhh, I'll do some more digging, the thing that puzzled me was that the problem is gone if I click on "Save" on the organization login policy (which presumably copies the settings from the instance, even though this happens https://github.com/zitadel/zitadel/issues/4552), and it is reappears if I click on "Reset to instance defaults".

**Comment by hifabienne** [comment] 2022-10-18 07:38
I will investigate some more time aswell.
Can you maybe create two organizations. One where it works and one where it doesn't. And then send me the organization ids in the discord. So we can compare the two settings.

**Comment by DavideWalder** [comment] 2022-10-18 07:57
Sure, I'll set them up. One detail I forgot to mention is that I'm not including the organization scope in the authorization request (I'm only giving `openid profile email urn:zitadel:iam:user:metadata`)

**Comment by DavideWalder** [comment] 2022-10-19 06:39
FYI: I just invited another user to the ZITADEL customer portal and we had the same issue (kept being redirected to the login page after logging in).

**Comment by hifabienne** [comment] 2022-10-24 14:15
Hei @DavideWalder 

Can you please try it again.
We have investigated some time and found a bug that might solve your problem.
We have deployed the newest version, and this might fix it.

**Comment by DavideWalder** [comment] 2022-10-24 14:32
Just tested with an instance running 2.10.0, same issue. I did the following:
- Picked an organization
- Reset the login policy to instance default (which has the URI)
- Tried logging in with an user of that organization -> redirection doesn't work
- Clicked on "Save"
- Redirection works

**Comment by hifabienne** [comment] 2022-10-25 08:45
@DavideWalder I think we found the bug.
We can see that the lifetimes on your instance login policies are all set to 0.
This means, that e.g password should be checked after 0 seconds, and results in staying on the password screen.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/38692350/197727674-4f50d50e-6836-4dd7-9980-756b13cff813.png">

**Comment by hifabienne** [comment] 2022-10-25 08:51
Is it possible that you have configured this somewhere and it is set to 0? Maybe terraform?

**Comment by DavideWalder** [comment] 2022-10-25 09:33
@hifabienne Thanks a lot for the find! I changed password check lifetime to 241 hours in the instance settings and it now works (no need to override the instance settings in the org)

I'm controlling the instance settings with a script (complementing the Terraform setup, since instance objects are not supported yet) where I'm in fact not specifying the lifetimes.

If I understand correctly there seems to be some defaulting login in the frontend (the displayed values do not match the actual ones), since I always see lifetimes as in the screenshot you posted even when they are 0.

**Comment by hifabienne** [comment] 2022-10-25 09:39
I am happy that we found the problem.

@peintnermax @livio-a I thought we changed the frontend to not showing some defaults? Is this not yet deployed?

**Comment by peintnermax** [comment] 2022-10-25 09:42
this will be fixed with https://github.com/zitadel/zitadel/pull/4575

**Comment by hifabienne** [comment] 2022-10-25 09:43
> this will be fixed with #4575

Great.

@DavideWalder I will close the issue, since we found the problem. With the fix on the other pr you should then also see if the values are not set.

**Closed by hifabienne** 2022-10-25 09:43 UTC
Labels: type: bug, category: backend, state: waiting
