### ISSUE TITLE
[Bug]: Authorize request return error login_required

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#7589] opened 2024-03-18 07:14 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.1

### Database

None

### Describe the problem caused by this bug

I got the error code login_required in zitadel site, when sent query params promp=none and id_token_hint=

I dont know why id_token_hint invalid 

so the quesition is: How the client application know that id_token_hint invalid before sending authoriztion request

detail error:
`
{ "error": "login_required", "error_description": "The id_token_hint is invalid. If you have any questions, you may contact the administrator of the application." }
`

reference: https://github.com/zitadel/zitadel/blob/6c3f48f49617478acfba89256d0dce62f6cb2d90/docs/docs/apis/openidoauth/endpoints.mdx#L152 

### To reproduce

It is flaky, i cant reproduce

**Comment by livio-a** [comment] 2024-03-20 09:08
duplicate of https://github.com/zitadel/zitadel/issues/5232

(has been fixed in 2.45)

**Comment by livio-a** [comment] 2024-03-20 09:08
duplicate of https://github.com/zitadel/zitadel/issues/5232

(has been fixed in 2.45)

**Closed by livio-a** 2024-03-20 09:08 UTC
Labels: bug, auth
