### ISSUE TITLE
[Bug]: If i name an Action with a Space inside, it doesn't work

### ISSUE THREAD

**Issue by hofq** [zitadel/zitadel#8751] opened 2024-10-09 14:19 UTC
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.51.3

### Database

None

### Database Version

spilo-16:3.3-p1

### Describe the problem caused by this bug

If I have a space in an Action Name, it doesn't work and shows no error in UI

### To reproduce

1. Go to Actions
2. Create an Action Named "groups Claim"
3. Insert wanted action
4. Save
5. Run a Request Against the Endpoint
6. See nothing done by the Action

### Expected behavior

The Name-Field should Regex the Name and throw an error if its not Supported

### Operating System

Device: Macbook, M2 Pro
Browser: Firefox 131.0

### Relevant Configuration

```js
/*
 * sets the roles an additional claim in the token with roles as value an project as key
 *
 * The role claims of the token look like the following:
 *
 * // added by the code below
 * "groups": ["{roleName}", "{roleName}", ...],
 *
 * Flow: Complement token, Triggers: Pre Userinfo creation, Pre access token creation
 *
 * @param ctx
 * @param api
 */
function groupsClaim(ctx, api) {
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) {
    return;
  }

  let grants = [];
  ctx.v1.user.grants.grants.forEach((claim) => {
    claim.roles.forEach((role) => {
      grants.push(role);
    });
  });

  api.v1.claims.setClaim("groups", grants);
}
```
The Action is setup with the Flow described in the Comment. 

### Additional Context

Renaming the Action to groupsClaim lets it run without any issues

**Comment by hifabienne** [comment] 2024-10-09 14:29
This is actually not a bug but works as intended.
The action name needs to be the same as the function in the javascript. 
It is described in this section here: https://zitadel.com/docs/apis/actions/introduction#action
And you can also see it here: ![Image](https://github.com/user-attachments/assets/4842ada6-2858-416f-8e42-e1e139d32a80)
Due to this i will close the issue

**Closed by hifabienne** 2024-10-09 14:29 UTC
Labels: bug
