### ISSUE TITLE
[Bug]: OAuthErrorEvent

### ISSUE THREAD

**Issue by mzch** [zitadel/zitadel#4807] opened 2022-12-01 15:54 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Don't show login page.

### To reproduce

1. start zitadel `v2.14.1`
2. visit login page.

### Screenshots

<img width="1476" alt="スクリーンショット 2022-12-02 0 51 13" src="https://user-images.githubusercontent.com/621178/205098634-ba513258-c5c1-486c-a524-62e359126ec0.png">

### Expected behavior

Show login page.

### Version

v2.14.1

### Operating System

- Client
Device: Mac
OS: macOS `13.0.1`
Browser: Google Chrome
Version: `108.0.5359.71`

- Server
OS: Debian `11.5`
DB: PostgreSQL: `15.1`

**Comment by adlerhurst** [comment] 2022-12-02 09:18
duplicate of https://github.com/zitadel/zitadel/issues/4604

**Closed by adlerhurst** 2022-12-02 09:18 UTC
Labels: type: bug, state: triage
