### ISSUE TITLE
[Bug]: Actions: users are sent to login before post creation trigger has run

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4808] opened 2022-12-02 08:42 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

In order to get an access token, the user must have the correct grants on the project, which are set in the post creation action. It seems like this trigger runs asynchronously, resulting in the user not being able to login.

### To reproduce

1. Setup an action to add user grants on post creation (which might take a few seconds to run)
2. Login with an external IDP
3. The user logs in before the action finishes and gets the message in the screenshot below.

### Screenshots

<img width="549" alt="Screenshot 2022-12-02 at 09 42 24" src="https://user-images.githubusercontent.com/58290976/205252025-3ec8d352-ea95-4b52-aa26-8eb5de4e40b8.png">

### Expected behavior

For single SSO applications, there should be a way to prevent a login if the post creation actions are still running.

### Version

2.14.1 (maybe also 2.13.1)

### Additional Context

In our case the action involves sending a request to an API which will create metadata and user grants, hence the long execution time.

Additionally, this might take longer than usual since we had to add a rate limiter to the Zitadel gRPC client (to avoid incurring in 429s from Zitadel Cloud, which can be easily triggered)

**Comment by DavideWalder** [comment] 2022-12-02 09:22
Linked to https://github.com/zitadel/zitadel/issues/4810

**Comment by livio-a** [comment] 2022-12-14 12:08
@hifabienne i could not reproduce it, but there might be a problem of eventual consistency

**Comment by DavideWalder** [comment] 2022-12-14 20:28
I haven't tried reproducing it yet. What I can suggest to reproduce is to:
- wait for some time in the action
- throw and error within the action

**Comment by hifabienne** [comment] 2023-01-16 13:41
ping @adlerhurst @livio-a

**Comment by livio-a** [comment] 2023-02-06 06:07
@adlerhurst wouldn't triggering the projection solve the problem?

**Comment by adlerhurst** [comment] 2023-02-06 06:47
> @adlerhurst wouldn't triggering the projection solve the problem?

If the code currently does not i would give it a try

**Comment by hifabienne** [comment] 2023-02-21 07:18
hei @DavideWalder I have created a user story according to this: https://github.com/zitadel/zitadel/issues/5254
Please subscribe to the new one as we will proceed there, and close this.

**Closed** 2023-02-21 07:18 UTC
Labels: type: bug, category: backend, state: triage
