### ISSUE TITLE
[Bug]: Endless loop after going back from login page

### ISSUE THREAD

**Issue by zilkf92** [zitadel/zitadel#8566] opened 2024-09-07 14:35 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Database

None

### Describe the problem caused by this bug

When I go back from the login page in the browser, I end up in an endless loop.

### To reproduce

1. Go to "home"
2. Go to "sign in"
3. Without entering any credentials, just click "back"
4. You will end up in an endless loop displaying "Signing you in..."

### Operating System

Browser: Google Chrome
Version: Version 127.0.6533.89 (Offizieller Build) (64-Bit)

**Comment by zilkf92** [comment] 2024-09-07 14:36
Reference website where the behavior occurred: https://photonq.org/

**Comment by kleberbaum** [comment] 2024-09-07 14:46
> Reference website where the behavior occurred: https://photonq.org/

### Instance Information of photonq.org
![IMG_20240907_163948_584](https://github.com/user-attachments/assets/6ab34813-c75f-463c-a725-330205ade074)

**Comment by schettn** [comment] 2024-10-28 06:52
@hifabienne  https://github.com/authts/react-oidc-context/issues/1243

**Comment by schettn** [comment] 2024-10-28 07:24
@hifabienne But I am not really sure if this is ZITADEL issue tho. The bug is related to frontend caching, thus the react state is not updated.. So the state is stuck in loading.

If someone at ZITADEL has encountered this issue when using the react-oidc-context library I would be happy to hear how they mitigated this.

**Comment by hifabienne** [comment] 2024-10-28 07:34
We recently heard from a customer that chrome does have a bug, where the session storage gets lost sometimes. 
Therefore it results in a redirect, as the user doesn't seam authenticated.
https://issues.chromium.org/issues/40940701

Could that be a potential problem?

**Comment by muhlemmer** [comment] 2024-10-30 08:10
Tried with Chromium `Version 130.0.6723.69 (Official Build) built on Debian GNU/Linux 12 (bookworm) (64-bit)` and can't reproduce. 

Indeed this is most likely a client issue and not a server / ZITADEL issue. Therefore we will close this issue.

**Closed by muhlemmer** 2024-10-30 08:10 UTC
Labels: bug, auth
