### ISSUE TITLE
HTTP ERROR 403 No valid crumb was included in the request only in CURL and JAVA client

### ISSUE THREAD

**Issue by sri1790** [zitadel/zitadel#5291] opened 2023-02-24 12:19 UTC
### Discussed in https://github.com/zitadel/zitadel/discussions/5279

<div type='discussions-op-text'>

<sup>Originally posted by **sri1790** February 23, 2023</sup>
I am trying to get token using the client credentials and getting success response in Postman and Go but same request is failing in Java and CURL. Please suggest.

**FAILURE**
<img width="988" alt="image" src="https://user-images.githubusercontent.com/23081940/220871821-24be5257-8223-44f2-a1ae-7eadacc12c7e.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/23081940/220872087-3b8be322-d753-4bac-b49f-ffc6f2ab9313.png">

**SUCCESS**

<img width="571" alt="image" src="https://user-images.githubusercontent.com/23081940/220872207-43ab2de7-91c4-40e3-90a9-033af5ffd767.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/23081940/220872538-e51740f4-e4d1-4cc6-9ebf-730d7bf22156.png">

</div>

**Comment by mffap** [comment] 2023-02-24 12:26
Hi @sri1790 is this a duplicate of the discussion?

**Comment by sri1790** [comment] 2023-02-24 12:36
Yes i created issue from discussion.

**Closed** 2023-02-24 12:42 UTC
