### ISSUE TITLE
Optimization: Registering > Username/PW instead of Registering > User selection

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#2096] opened 2021-07-29 06:18 UTC
A suggestion for a better user flow on the registering form:

If a person has more than one registered user and they register a new one, nstead of leading the user to this prompt:

![image](https://user-images.githubusercontent.com/48990649/127441132-8c6951b6-179d-4c69-9041-070b04540f18.png)

redirect them here (ideally with pre-filled username)

![image](https://user-images.githubusercontent.com/48990649/127441208-81bde5dc-f7e1-492e-be63-4e757a4d4841.png)

Because the user could be misslead that he has to login with his other account for some reason.

**Edit: As discussed yesterday, we should even aim for a complete skip of the additional password/MFA prompt, as the user already entered it in the registering process.
Alternatively, leave it as a option for the org owner to decide**

**Comment by juergrinaldi** [comment] 2022-08-15 08:23
Just hitting this for the 'stale status'. This is still relevant in V2 and as such should be tackled in the near future.

**Comment by juergrinaldi** [comment] 2022-08-17 10:53
Edit: As discussed yesterday, we should even aim for a complete skip of the additional password/MFA prompt, as the user already entered it in the registering process.
Alternatively, leave it as a option for the org owner to decide

**Comment by hifabienne** [comment] 2022-12-28 14:02
I think this is a duplicate of #4059 
I will close this one, if I am wrong feel free to reopen

**Closed by hifabienne** 2022-12-28 14:02 UTC
Labels: lang: go, category: backend
