### ISSUE TITLE
[Bug]: Organization Message Texts and Interface Texts settings are not linked to instance by default and have no button to sync them

### ISSUE THREAD

**Issue by honzapatCZ** [zitadel/zitadel#5299] opened 2023-02-25 17:13 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Organization settings of texts(email, etc.) are by default not linked. Changes made on the instance are not propagated to organizations. Further more the usual "Sync" button is missing.

### To reproduce

1. Change Message Text Settings on Instance
2. Check that they have not been changed on unmodified organizations - non logical bug?
3. Observe that the button to sync them is missing - bug for sure.

### Version

latest Cloud

**Comment by hifabienne** [comment] 2023-02-27 01:21
Hei @honzapatCZ 
I am not sure If I understand you problem correct.
The instance settings are the default settings for all organizations.
As long as you don't overwrite the settings on the organization, the settings from the instance will be triggered.
As soon as you overwrite them on the organization you will not get the updates anymore.
There is no need to sync it as it is automatically like this.

Or do you want to sync back from an organization to the instance?

**Comment by honzapatCZ** [comment] 2023-02-27 06:56
But the organization settings does not reflect the instnace changes(when not overwitten).
Futher more, when there are changes on the organization settings(regarding texts) the sync button is missing

**Comment by hifabienne** [comment] 2023-03-03 03:43
I just have tested the behaviour. And I think the confusion is, because we do not handle the login texts the same as the message texts.

Login UI Texts:
Each text is handled separatly.
If one text is overwritten on the the organisation. The others will automatically be the texts from the instance. Only the overwritten text will not change if something changes on the instance.

Message Texts:
One Message with all texts is handled together. This means if one text is overwritten, the whole email/message template is overwritten, and you will not get the update of the instance anymore.

This works currently as intended. We probably have to make this more clear with some descriptions. But if we see that there is a need from a lot of customers we can have a look at changing this behaviour in the future.

**Comment by honzapatCZ** [comment] 2023-03-03 15:52
> I just have tested the behaviour. And I think the confusion is, because we do not handle the login texts the same as the message texts.
> 
> Login UI Texts: Each text is handled separatly. If one text is overwritten on the the organisation. The others will automatically be the texts from the instance. Only the overwritten text will not change if something changes on the instance.
> 
> Message Texts: One Message with all texts is handled together. This means if one text is overwritten, the whole email/message template is overwritten, and you will not get the update of the instance anymore.
> 
> This works currently as intended. We probably have to make this more clear with some descriptions. But if we see that there is a need from a lot of customers we can have a look at changing this behaviour in the future.

At the very least the "Sync" button is missing

**Comment by hifabienne** [comment] 2023-10-16 14:48
I will close this issue for now, as it works as designed and I don't see the need to implement something additional for now.

**Closed by hifabienne** 2023-10-16 14:48 UTC
Labels: bug
