### ISSUE TITLE
[Bug]: Internal login when using external idP

### ISSUE THREAD

**Issue by Aurel004** [zitadel/zitadel#8924] opened 2024-11-19 00:27 UTC
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.65.1

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

Hi,

I have a setup that uses internal login or external login (Github, LDAP)

I have linked an internal login with and external login (so I could use both for 1 account)

The thing is, once an external login is linked to the account, I can only login with the external way, even if I do not click on LDAP/Github and enter my internal username, when I click next, I’m redirected to the external login form.

It’s nice until the external provider is out. For example, if the LDAP server is shut down, when I want to login with my internal login, it redirects me to LDAP and then I have an error telling me that it can’t reach the LDAP server. And then, I’m locked out

The only way to login back with internal login is to remove the external idP of the account, or I am missing something ?

Thanks

### To reproduce

Setup internal login
Setup any external idP
Allow both methods to connect
Link your 2 accounts
Try to connect with your internal login

**Comment by muhlemmer** [comment] 2024-11-27 08:06
Currently works as intended. We have a enhancement issue open to change this behavior: https://github.com/zitadel/zitadel/issues/6466. Closing as duplicate.

**Closed by muhlemmer** 2024-11-27 08:06 UTC
Labels: bug, auth
