### ISSUE TITLE
[Bug]: Invalid token when upgrade zitadel version

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#6945] opened 2023-11-21 03:00 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.0

### Describe the problem caused by this bug

Forward from discord post: https://discord.com/channels/927474939156643850/1174568573503553626

As a developer, when I upgraded from self-host zitadel from v2.37.1 to v 2.41.0, I got an invalid token error when make first request to management API, the second request successfully

### To reproduce

1. In docker compose file: update image version from **v2.37.1** to **v2.41.0**, update command from `zitadel start` to `zitadel start-from-setup`
2. docker compose up
3. run test cases (all test cases already successful in v2.37.1)
=> Got error Invalid token in new version (v2.41.0)
=> I tried to rollback old version (v2.37.1) => all test cases successfully again 

### Screenshots

![Screen_Shot_2023-11-16_at_11 34 52](https://github.com/zitadel/zitadel/assets/25562869/401d525f-9a5d-46ee-8ad5-c26f18fb7f4a)

**Comment by hifabienne** [comment] 2023-11-22 07:37
@adlerhurst @livio-a Is this issue handled with https://github.com/zitadel/zitadel/issues/6949 ?

**Comment by livio-a** [comment] 2023-11-22 07:45
> @adlerhurst @livio-a Is this issue handled with https://github.com/zitadel/zitadel/issues/6949 ?

Yes this issues seems ti be a copy from the discord chat linked #6949

**Comment by hifabienne** [comment] 2023-11-22 07:46
hei @quochuydev 
I will close this issue as it is a duplicate of the other one, to keep the repository clean.
Please subscribe to the other issue

**Closed by hifabienne** 2023-11-22 07:46 UTC
Labels: bug
