### ISSUE TITLE
[Bug]: Domain Discovery should be case insensitive

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5638] opened 2023-04-07 18:10 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

[discord chat](https://discordapp.com/channels/927474939156643850/1093564731425570906)  

my domain is idaho2324.onmicrosoft.com

PASS: When I enter the user test@idaho2324.onmicrosoft.com it redirects to azureAD.
FAIL: when I enter TEST@IDAHO2324.ONMICROSOFT.COM I get a User could not be found.

### To reproduce

see screen shot

### Screenshots

![image](https://user-images.githubusercontent.com/201257/230656867-3fc9be7f-d48a-47eb-b018-b68e55e96b21.png)
![image](https://user-images.githubusercontent.com/201257/230656889-2775c11a-481f-45fe-8df0-7ee004de438f.png)
![image](https://user-images.githubusercontent.com/201257/230656902-a600745f-0742-41db-9e64-49b1cfe962ef.png)

### Expected behavior

domains and emails are not case sensitive.  Users will type in any variation of cases in their emails and domain.

### Version

   image: 'ghcr.io/zitadel/zitadel:v2.23.0'

**Comment by doncicuto** [comment] 2023-04-24 17:23
@hifabienne I guess this is a duplicate of #5647. I could try to tackle this issue as well as issue #5579 that is somehow related if you want to assign both of them to me.

**Comment by hifabienne** [comment] 2023-04-25 05:20
Hei @doncicuto 
That would be great. Thanks

**Comment by hifabienne** [comment] 2023-06-19 08:04
Hei @doncicuto 
I am just going through the open issues. Are you working on this?
Or should I put it back to the backlog?

**Comment by doncicuto** [comment] 2023-06-19 21:19
Hi @hifabienne I'd like to continue with this issue but you may put It to the backlog as I wont have time to revisit it this week.  I've been working on other issues that were quicker for me to fix them but I'll try to continue with this one soon. I'll let you know once I've implemented It. Thanks!

**Closed** 2023-07-12 13:02 UTC
Labels: bug
