### ISSUE TITLE
Yubikey not working for passwordless on Firefox+Ubuntu

### ISSUE THREAD

**Issue by kpetremann** [zitadel/zitadel#4082] opened 2022-07-31 09:23 UTC
**Describe the bug**

On Firefox on linux (Ubuntu):
* my Yubikeys are not recognized when trying to register in the console in passwordless section
* cannot use a Yubikey to log in via passwordless (after successfully registered it via Chrome)

During authentication, I got the following error:
![image](https://user-images.githubusercontent.com/13746171/182019571-9cfa994d-5940-4421-a114-ab68657e4033.png)

Yubikey works:
* perfectly for MFA on Firefox and Chrome
* perfectly as passwordless method on Chrome
* perfectly as passwordless method on Firefox+Windows11

Note: I tried two different Yubikeys: Yubikey Bio, and YubiKey 5C

**Expected behavior**
Registering and using a Yubikey as passwordless method should work on Firefox.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox 103
 - Version: v2.0.0

**Comment by fforootd** [comment] 2022-07-31 09:46
Thanks for reporting this.

I will reproduce this tomorrow on my windows 11 machine with a yubikey 5c.

Can you for me Test if windows hello works?

Because I use windows hello on a daily basis but haven't used my yubikey in a while on windows 😅

**Comment by fforootd** [comment] 2022-07-31 09:46
@livio-a i will report my results here

**Comment by kpetremann** [comment] 2022-07-31 10:02
Windows Hello works perfectly :)

**Comment by kpetremann** [comment] 2022-07-31 10:08
Oh, I just retested on Windows and it works! Windows Hello was just keeping the priority over the Yubikey (on registration).

So I'll edit the issue: it is only not working on Ubuntu+Firefox actually.
(sorry about that)

**Comment by fforootd** [comment] 2022-08-01 07:39
> So I'll edit the issue: it is not working only on Ubuntu+Firefox actually.

Thanks for this feedback. Just to be certain, does it work on other sites? Just to exclude the linux settings.

**Comment by kpetremann** [comment] 2022-08-01 08:27
> does it work on other sites

yes it does. I just tested again with Keycloak.

**Comment by fforootd** [comment] 2022-08-01 08:34
Nice, thank you for verifying. I need to setup a linux vm to test this since I mainly use WSL2 and MacOS

@eliobischof since you use an Ubuntu as daily driver, can you test how your hardware key works with ZITADEL?

**Comment by livio-a** [comment] 2022-08-02 07:00
@fforootd we had a similar issue https://github.com/zitadel/zitadel/issues/2910 which occurred rarely and I could never reproduce it.

**Comment by fforootd** [comment] 2022-08-09 07:31
I tried many different solutions to reproduce this one in a Ubuntu vm. But I could not get it reproducible results 😢 

@eliobischof since you use Ubuntu as your daily driver... what happens with Firefox and hardware keys when you use ZITADEL?

**Comment by eliobischof** [comment] 2022-08-09 09:36
I'll test it as soon as I have a hardware token. I expect the delivery tomorrow or the day after.

**Comment by eliobischof** [comment] 2022-08-10 14:54
I can confirm, it doesn't work with Ubuntu 20.04, Firefox 103 and Yubikey 5C.

Tried with a Firefox installation over GNOME Software as well as apt-get. The result is the same.

Chrome asks for the Yubikey password, Firefox doesn't.

**Comment by fforootd** [comment] 2022-08-10 14:55
What happens if you use a demo page like https://webauthn.io/

**Comment by eliobischof** [comment] 2022-08-10 15:08
works

**Comment by fforootd** [comment] 2022-08-10 15:09
> works

Ok so we need to investigate in that case

**Comment by livio-a** [comment] 2022-08-11 07:11
Just tried with an old SoloKey 1.2 on macOS 12.4, FF 103.0.2 and Safari 15.5
seems like FF does not support User Verification:
![image](https://user-images.githubusercontent.com/9405495/184076353-5eb34422-8ce4-49f3-9ec1-5c7ba1304fde.png)
![image](https://user-images.githubusercontent.com/9405495/184077416-842b7153-1718-4669-81f6-2dd235700cbf.png)

I then tested multiple combinations and Safari as well:

| Browser | Registration | Login            | Result | Remark |
| -------- | ------------ | ------------ | ------ | -------- |
| FF          | discouraged | discouraged | ✅     |                |
| Chrome | discouraged | discouraged | ⚠️      | PIN prompt on login |
| Safari    | discouraged | discouraged |  ❌     | PIN prompt on register and login; no credentials found on login |
| FF          | discouraged | required        | ⚠️       | logged in without PIN prompt |
| Chrome | discouraged | required        | ⚠️       | PIN prompt on login |
| Safari    | discouraged | required        | ❌      | PIN prompt on register and login; no credentials found on login |
| FF          | required        | discouraged | ❌      | no PIN prompt; registration aborted
| Chrome | required        | discouraged | ⚠️       | PIN prompt on both
| Safari    | required        | discouraged | ❌      | PIN prompt on register and login; no credentials found on login |
| FF          | required        | required        | ❌      | no PIN prompt; registration aborted
| Chrome | required        | required        | ✅     |              |
| Safari    | required        | required        | ❌      | PIN prompt on register and login; no credentials found on login |

It might well be that i need to update the Firmware on this SoloKey, but the only Browser that worked was Chrome.
I would need to check the specs if a PIN prompt is ok e.g. for `discouraged` on login but registered with `required`.

**Comment by fforootd** [comment] 2022-08-11 07:22
@livio-a in the office are new yubikeys 5 and 5c for testing purpose. Lets also test one of those.

Let me know If none one is left of them.

**Comment by livio-a** [comment] 2022-08-11 08:55
OK I've now retested with a Yubikey 5c and the same setup as above.

Started with Safari which, at, first never prompted for a PIN even if required.
Then switched to Firefox which does not activate the key if user verification is required.
With the first required user verification in Chrome, I had to create a PIN, which is now respected / prompted in Safari as well (login now works there as well; seems like an issue with the old SoloKey).

Current state (after initial PIN set):
- Firefox only works if user verification is not `required` on registration, it will then ignore it on login
- Safari always prompts even on `discouraged` (registration and login)
- Chrome always prompts on login even on  `discouraged`

**Comment by fforootd** [comment] 2022-09-12 22:11
Firefox (at least the snap version) on Ubuntu is definitely broken when a PIN is set.

I need to investigate further what the problem is.

**Comment by kpetremann** [comment] 2022-09-19 12:25
> Firefox (at least the snap version) on Ubuntu is definitely broken when a PIN is set.

I've just tested, the non-snap Firefox (.deb) also has the problem

**Comment by fforootd** [comment] 2022-09-21 20:50
> I've just tested, the non-snap Firefox (.deb) also has the problem

Same on fedora with Firefox on the other hand Chrome works like a charm.

**Comment by hifabienne** [comment] 2023-01-03 12:37
I will close this issue, because it is a problem with Firefox, and we are not able to do something about it right now.

**Closed by hifabienne** 2023-01-03 12:37 UTC
Labels: type: bug, help wanted, priority: medium

**Comment by kpetremann** [comment] 2023-01-03 14:03
hello @hifabienne
Sure, I get it.

Just two quick questions: 
- why is it working with Keycloak and not Zitadel? is it using a different Firefox API/implem?
- do you know if there is an issue to track this on Firefox side?

**Comment by livio-a** [comment] 2023-01-04 08:20
Hey @kpetremann 

I did some research and found the following:
- According to https://wiki.mozilla.org/Security/Web_Authentication FF uses https://github.com/mozilla/authenticator-rs for WebAuthN. The library currently uses CTAP1 (U2F / second factor) and there is CTAP2 (multi factor) branch (which seems abandoned)
- WebAuthN allows multiple options during registration and login. One of it is user verification, which means the user has to somehow verify himself to unlock the key generation / verification. This can be either a biometric check or entering a PIN.
- In ZITADEL we currently do require a user verification for passwordless login as we use it as multifactor authentication (no additional second factor check required). But iff you use the Yubikey as 2FA, you won't be prompted for user verification, as we do not require it there.
- In Keycloak you can specify the user verification for both WebAuthN authentications and the default for passwordless is `not specified`, which then defaults to the WebAuthN default `preferred` and work with FF
<img width="346" alt="image" src="https://user-images.githubusercontent.com/9405495/210512336-704190ac-b350-425c-aff2-d0d704d08401.png">

**Comment by kpetremann** [comment] 2023-01-04 12:57
hello @livio-a,

Many thanks for the explanation it is crystal clear.
