### ISSUE TITLE
[Bug]: non-required field is required in Update User Profile API

### ISSUE THREAD

**Issue by aalexren** [zitadel/zitadel#6124] opened 2023-06-30 15:43 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.28.1

### Describe the problem caused by this bug

I try to call API method like defined in docs: https://zitadel.com/docs/apis/resources/mgmt/management-service-update-human-profile

My request URL seems like:
`localhost:8080/management/v1/users/220111235683778563/profile`

With request body:
```
{
    "firstName": "John",
    "lastName": "Doe"
}
```

And with the Authorization header:
`Bearer Cee0MVgnkKSeR1NGzKnavBzNsCqKqcEFtbKUi0TCUAwi-HaSvuoayitRmYMoGRjPNAz7u70`

I try to make a call keeping in mind that only two fields are required: firstName and lastName. But it gives me error:
`"message": "invalid UpdateHumanProfileRequest.DisplayName: value length must be between 1 and 200 runes, inclusive"`

### To reproduce

1. Make Zitadel instance, make an common user
2. Create service "super" user with PAT
3. Make CURL request:

```
curl -L -X PUT 'http://localhost:8080/management/v1/users/220111235683778563/profile' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer Cee0MVgnkKSeR1NGzKnavBzNsCqKqcEFtbKUi0TCUAwi-HaSvuoayitRmYMoGRjPNAz7u70' \
--data-raw '{
  "firstName": "John",
  "lastName": "Doe"
}'
```

4. Get an erorr

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/25721843/e2cb9f79-2435-432c-b14e-1be612704d29)

### Expected behavior

Expect OK 200 success

### Operating System

Device: Macbook Air 2015 13'
OS: macOS 12.6.7 Monterey
Client: cURL 7.87.0

**Comment by hifabienne** [comment] 2023-07-03 06:50
Hei @aalexren 
Thanks for your report.
You are right. Generally the first and lastname are the only required fields when creating a user.
We do compute the Displayname from those fields, so we can use it in emails, and for display porpuse.
Normally we just take Firstname + Lastname. Considering that in the future we will also make first and lastname optional, it would take the email address in case of no first and lastname.

This said, as soon as the display name is set the first time it gets required.

I see some possible solutions:
1. Leave it like it is, and require the user to set the display name on the update.
2. When the display name ist not set in the update request, compute it again from the data we have (This could potentially overwrite something that has been set)
3. When no display name is set, leave what is already on the user

@livio-a @muhlemmer what do you think?

**Comment by muhlemmer** [comment] 2023-07-03 08:29
I think the "bug" here is the omission of the `(google.api.field_behavior) = REQUIRED` option for the `display_name` field, resulting in confusing documentation. The validator rules are also part of the proto, thus of the API contract and documentation:

https://github.com/zitadel/zitadel/blob/3f85aa014e907af220879329eb75be7b7f2bfb99/proto/zitadel/management.proto#L7771-L7778

Renders like:

![image](https://github.com/zitadel/zitadel/assets/5411563/d94db020-dd13-4cd3-8f62-d3bac8828d83)

It does say the value should be`non-empty`. Compare with `nickName` which is truly a optional field, as it does not have the `non-empty` keyword.

----

Re @hifabienne

> 2. When the display name ist not set in the update request, compute it again from the data we have (This could potentially overwrite something that has been set)

This could be achieved by using the `optional` keyword in the proto file. In Go code this would result in a pointer to a string:

1. If the value is unset, `nil` pointer, do not change the display name nor compute anything;
2. If the value is set to an empty string, it will mean "unset" and we compute the new display name;
3. If the value is set to a string, update the display name accordingly;

Another way would be to use a `oneOf` of `string display_name` and `bool compute_display_name`.

Both solutions will mean a breaking change, because the generated code for the clients will look different. (Such a the pointer to string in Go). So we should move such a change to the v2 API instead.

**Comment by stebenz** [comment] 2024-03-12 17:38
@hifabienne Should here still be made a change or do we close this issue in favor of user v3?

**Comment by hifabienne** [comment] 2024-03-13 07:16
I think it would be an easy fix to make it optional and compute the field also in the update method.
Depending on when we could implement we should just do it, or would that be a breaking change?

**Comment by hifabienne** [comment] 2024-03-13 14:08
> Is this meant for the user v2? If so, v2 is with partial update how do we handle the display name there? (I have no idea if the display name is computed or not, but still can be updated, as it will be at least be set through the create)
> 
> Yes it will still be a "breaking change", which would not be as bad in the V2, but all in all it would take only small changes to achieve this "fix".

The issue talks about the mgmt api, this is v1.
So it should be fixed there. But we should also think about how this should be solved in the newer versions.

**Comment by muhlemmer** [comment] 2024-03-20 10:05
As I pointed out, the issue is a documentation render and can easily be solved for v1:

> I think the "bug" here is the omission of the (google.api.field_behavior) = REQUIRED option for the display_name field, resulting in confusing documentation. The validator rules are also part of the proto, thus of the API contract and documentation:

For auto-computation we need a breaking change, so it should go into v2 or might be postponed until user schema / v3.

**Comment by adlerhurst** [comment] 2024-03-22 09:49
the required flag was added. do we need to keep it open for v3? @hifabienne 

as v3 allows partial updates display name must be updated separately IMO

**Closed** 2024-03-22 09:50 UTC
Labels: bug, backend, resources
