### ISSUE TITLE
[Bug]: email verified, doesn't work in user edit 

### ISSUE THREAD

**Issue by chezgi** [zitadel/zitadel#6777] opened 2023-10-23 04:56 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.39.1

### Describe the problem caused by this bug

in user edit dialog, when changing user domain, email verified checked, doesn't work

### To reproduce

1- in user edit dialog
2- change user domain
3- tick email verified checkbox

### Screenshots

![Screenshot from 2023-10-23 08-27-37](https://github.com/zitadel/zitadel/assets/309195/af783d71-e61e-45ef-bdc7-60745862b0a2)
![Screenshot from 2023-10-23 08-28-06](https://github.com/zitadel/zitadel/assets/309195/3497d755-dbd9-4333-ab96-883395ef3346)
![Screenshot from 2023-10-23 08-28-24](https://github.com/zitadel/zitadel/assets/309195/3274709d-2073-4c0d-9a86-6c15eaa91a11)

**Comment by hifabienne** [comment] 2023-10-23 06:14
Hei @chezgi 
Thanks for reporting this issue.
I have verified and it looks like the frontend doesn't send the verified bool.

**Comment by chezgi** [comment] 2023-10-24 04:12
Hi @Universe-stack,
I don't have permission to assign persons to issues.

**Comment by Universe-stack** [comment] 2023-10-24 05:00
I understand. Maybe @hifabienne can. Hi @hifabienne , can you assign me to this task? Thanks.

**Comment by hifabienne** [comment] 2023-10-24 06:26
Hei @Universe-stack 
Thanks for your offer.
I assigned you

**Comment by Universe-stack** [comment] 2023-10-24 14:25
Thanks..

**Comment by Universe-stack** [comment] 2023-10-24 16:05
I reviewed the form on the website to confirm the above issue but I didn't encounter it. Below is a video to verify. 

After changing my email on the form, the **verified** tag turned to **unverified** and I had to request for a code to verify the new email again. I think this works as expected. Please correct me if I'm wrong.

Thanks.


https://github.com/zitadel/zitadel/assets/76141133/5386678d-cc87-4472-b3f7-e9c5ee0182e9

**Comment by hifabienne** [comment] 2023-10-25 06:08
hei @Universe-stack 
The screen recording you show, is from the customer portal. this is not included in this github repository (zitadel/zitadel), as it is private, because we need it to manage our SaaS service.

The right place is when you go to your instance domain https://acme-dxzbrv.zitadel.cloud/ then to users, and to a specific detail of a user.
<img width="989" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/e1be4178-bead-43c8-8c53-7e4882b12a10">

**Comment by hifabienne** [comment] 2023-10-27 07:12
hei @Universe-stack 
The expected behavior is that when I change the email, and enable email verified, that the email is directly verified, without sending a code to the email address.
The API already allows that, you can send email_verified as a bool = true, if the checkbox is enabled in the ui.

The code of the console is not private, only of the customer portal.
You can find it here: https://github.com/zitadel/zitadel/tree/main/console

**Comment by hifabienne** [comment] 2024-01-16 09:59
hei @Universe-stack 
Do you still work on this issue?

**Comment by Universe-stack** [comment] 2024-01-17 17:39
Yes Fabi. Thanks for reminding me.

**Comment by doncicuto** [comment] 2024-07-12 11:34
Hei @hifabienne I think this issue can be closed as it was fixed in #7844

**Comment by hifabienne** [comment] 2024-07-12 13:28
thanks @doncicuto

**Closed** 2024-07-12 13:27 UTC
Labels: bug, good first issue, frontend
