### ISSUE TITLE
Back arrow button returning to wrong Organization login form.

### ISSUE THREAD

**Issue by yasukawa426** [zitadel/zitadel#4069] opened 2022-07-28 16:23 UTC
**Describe the bug**
Whenever you press the back arrow button, be it at the email confirmation screen after creating a new user or at the 2FA form screen, you get sent to the wrong Organization (another organization instead of the same one) login form. Same happens both on mobile and web.

**To Reproduce**
1. Register a new user
2. Press the back arrow when asked to verify your email
3. Get sent to the wrong organization login

or 

1. Login with your account
2. Press the back arrow when asked your 2FA
3. Get sent to the wrong organization login

**Expected behavior**
You should be sent back to the same Organization login form where you started.

**Screenshots**
| Organization Login where I start |
| ------------------------------------ |
| ![right org](https://user-images.githubusercontent.com/62857460/181586890-b12446cb-4c3d-4b4f-bc67-64da8bd6b7e3.png) |

| 2FA back arrow | Email confirmation back arrow|
| ----------------- | --------------------------------- |
| ![2fa](https://user-images.githubusercontent.com/62857460/181586830-62ebc5e2-b918-41d4-82d7-8649c2877e80.png) | ![confirmation](https://user-images.githubusercontent.com/62857460/181587183-bc621f53-2d17-4562-9a11-821f42beac27.png) |

| Wrong domain I get sent after pressing the back arrow | 
| ------------------------------------------------------------- |
| ![image](https://user-images.githubusercontent.com/62857460/181587609-984cb91d-74c0-4d76-9c55-15f2d6ff97ea.png) |

**Desktop:**

 - OS: Windows 10
 - Browser: Chrome
 - Version 103.0.5060.114 (Versão oficial) 64 bits

**Smartphone:**
 - Device: Redmi Note 10
 - OS: Android 11 RKQ1.201022.002. MIUI Global 12.5.5
 - Browser: Chrome
 - Version 103.0.5060.71

**Additional context**
I have both a "ZITADEL" organization and a "Stolz Labs" organization, "Stolz Labs" being the correct one that I should be sent to.

**Comment by hifabienne** [comment] 2022-08-02 11:35
Hi @yasukawa426 Thanks for your report

I just tested this myself and could not reproduce it.

Can you answer this question, so I am able to set the same settings as you have?
Do you send a primary domain scope on your authorization request to select the organisation?
Is the problem that you branding doesn't trigger?
How did you configure your branding? On the instance settings or on the organization?

We recommend to set the branding setting on your organisation, in this case you will always see the correct logo/colors, etc.
If you need for a customer another branding you can overwrite it on the specific organisation.

I assume that the problem is, that you instance doesn't have a logo set. As soon as you go back to the "select account" screen we don't know which user you choose and are not able to trigger the settings from a specific organisation. In this case always the settings from the instance trigger.

It would also be possible to set a setting on your application to always trigger the branding of the organisation where the project belongs to.

**Comment by mffap** [comment] 2022-08-19 08:12
Hi @yasukawa426 just a reminder for the questions of @hifabienne . Do you have some feedback to the questions? Thanks.

**Comment by hifabienne** [comment] 2022-12-29 07:42
I will close this issue since we do not get an answer and can't reproduce. Feel free to reopen, when it appears again and you can answer my questions.

**Closed by hifabienne** 2022-12-29 07:42 UTC
Labels: type: bug, category: frontend, state: waiting, priority: medium
