### ISSUE TITLE
[Bug]: Selfhosted Postgresql could not obtain lock on row in relation "current_states"

### ISSUE THREAD

**Issue by gandalfb** [zitadel/zitadel#7710] opened 2024-04-05 07:59 UTC
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.49.1

### Database

PostgreSQL

### Database Version

postgres:16-alpine

### Describe the problem caused by this bug

Functionality seems to be not affected, but I wonder what this means or breaks.
I.e. I was not able to use triggers and add static claims as stated within documentation... but this could be something else.

Using opague tokens with service user (basic auth + jwt private key)

Thank you!

```
db-1       | 2024-04-XX 03:55:47.384 UTC [658] ERROR:  could not obtain lock on row in relation "current_states"
db-1       | 2024-04-XX 03:55:47.384 UTC [658] STATEMENT:  SELECT
db-1       |        aggregate_id
db-1       |        , aggregate_type
db-1       |        , "sequence"
db-1       |        , event_date
db-1       |        , "position"
db-1       |        , filter_offset
db-1       |    FROM
db-1       |        projections.current_states
db-1       |    WHERE
db-1       |        instance_id = $1
db-1       |        AND projection_name = $2
db-1       |    FOR UPDATE NOWAIT;
zitadel-1  | time="2024-04-XXT03:55:47Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="https://iam.mcp.buscher.xyz" grpcStatus= httpStatus= instance=<id> isSystemUser=false method= org=<id>path=/oauth/v2/token requestMethod=POST trigger=accessToken user=<id>
```

### To reproduce

Using opague tokens with service user (basic auth + jwt private key) and request a token for a **serviceuser**

```
POST {{baseUrl}}/oauth/v2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{user}}:{{password}}

grant_type=client_credentials&scope=openid profile urn:zitadel:iam:org:project:id:{projectId}:aud
```

### Relevant Configuration

Tried recreate with `--init-projections=true` (without deleting data)

**Comment by arustamyansv** [comment] 2024-04-18 15:26
have the same issue with PostgreSQL 15 (Cloud SQL on Google Cloud).

Here is a list of errors that I can observe in the pod log 


```

time="2024-04-09T14:59:12Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:416" error="sql: transaction has already been committed or rolled back" projection=projections.apps6

time="2024-04-09T14:59:16Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:629" error="ID=CRDB-pKtsr Message=exec failed Parent=(sql: transaction has already been committed or rolled back)" projection=projections.apps6

time="2024-04-09T14:59:16Z" level=warning msg="unable to get failure count" aggregate=261811373993033834 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=261811373992837226 projection=projections.apps6 sequence=14


time="2024-04-09T14:59:16Z" level=warning msg="unable to update state" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/state.go:96" error="sql: transaction has already been committed or rolled back" projection=projections.apps6

```

**Comment by fforootd** [comment] 2024-04-18 15:45
Thanks for raising this. Actually we have spotted such errors as well on our GCP infra.

Let us look into this, but ATM we assume that it does not have an immediate harm.

**Comment by pot-code** [comment] 2024-06-11 04:30
@fforootd the harm is it rockets the cpu usage, makes it unusable

**Comment by fforootd** [comment] 2024-06-11 08:35
@pot-code what version are you using with what config?

**Comment by pot-code** [comment] 2024-06-11 09:31
@fforootd 

OS: windows11 Home Edition 23H2
Env: docker
Zitadel: ghcr.io/zitadel/zitadel:latest
DB: postgres:16-alpine

docker compose file was pulled from Zitadel doc.

it happens after updating the zitadel image from v2.41 (if i remember it correctly), then docker recreted the container and boom

after a reboot the problem is gone and now i'm struggling with the `FATAL:  role "root" does not exist` and `could not obtain lock on row` issues

**Comment by ilyavaiser** [comment] 2024-06-11 12:12
Same problem here

**Comment by pot-code** [comment] 2024-06-12 01:11
@fforootd guess i figured it out, it may be caused by the double render in React (when StrictMode is turned on). 

the lock error is gone after removing it

**Comment by fforootd** [comment] 2024-06-12 11:56
Do you both see the same if you deploy a fresh v2.54.2 instance?

**Comment by pot-code** [comment] 2024-06-14 01:11
@fforootd reproduced in v2.53.3, on macOS

```
2024-06-14 01:07:43.793 UTC [1296] ERROR:  could not obtain lock on row in relation "current_states"
2024-06-14 01:07:43.793 UTC [1296] STATEMENT:  SELECT
	    aggregate_id
	    , aggregate_type
	    , "sequence"
	    , event_date
	    , "position"
	    , filter_offset
	FROM 
	    projections.current_states
	WHERE
	    instance_id = $1
	    AND projection_name = $2
	FOR UPDATE NOWAIT;
2024-06-14 01:07:50.773 UTC [1802] FATAL:  role "root" does not exist
2024-06-14 01:08:00.836 UTC [2189] FATAL:  role "root" does not exist
2024-06-14 01:08:10.880 UTC [2344] FATAL:  role "root" does not exist
```

**Comment by fforootd** [comment] 2024-06-14 09:06
As far as we are aware the error `could not obtain lock on row in relation "current_states"``happens from time to time and should not be worry some.

But `FATAL:  role "root" does not exist` is a weird one... can you share your zitadel config?

**Comment by pot-code** [comment] 2024-06-14 09:33
the config is simply pulled from zitadel self-host example. i could get ride of the error by setting another `PGUSER` environment variable

**Comment by fforootd** [comment] 2024-06-14 09:42
@pot-code ok thanks for sharing. Re: CPU, can you try 2.53.6 that contains a fix for a CPU problem we had  (or 2.54.3)

The CPU might relate to this issue #8059

**Comment by pot-code** [comment] 2024-06-14 10:54
@fforootd that's a relief! thank you

**Comment by geromueller** [comment] 2024-07-01 09:54
This is still not fixed for me. This looks like it might be related: https://github.com/jackc/pgx/issues/831

**Comment by zicklag** [comment] 2024-07-07 13:53
I am having the same issue in my Docker setup. I only just noticed the issue even, though I haven't changed anything ( maybe the server could have restarted, but I don't think so ).

zitadel:

    image: 'ghcr.io/zitadel/zitadel:v2.55.2'

postgres:

    image: postgres:16-alpine


I was also getting the `FATAL:  role "root" does not exist`, but then I fixed that by adding `user: postgres` to the Docker compose service for the database. Apparently the database wants to run with the same system user as the database or something.

But that seems unrelated to the zitadel issue now.

I also had the issue with zitadel version `ghcr.io/zitadel/zitadel:v2.48.2`, but I upgraded to `v2.55.2` to try and fix the issue.

Here's my error:

```
2024-07-07 13:43:15.106 UTC [2303] ERROR:  could not obtain lock on row in relation "current_states"
2024-07-07 13:43:15.106 UTC [2303] STATEMENT:  SELECT
	    aggregate_id
	    , aggregate_type
	    , "sequence"
	    , event_date
	    , "position"
	    , filter_offset
	FROM 
	    projections.current_states
	WHERE
	    instance_id = $1
	    AND projection_name = $2
	FOR UPDATE NOWAIT;
```

**Comment by mf-in-mun** [comment] 2024-07-23 06:13
I got the same error since I've started with Zitadel (2.54.3) . I've updated to 2.56.2 this morning.
The error is still there.
I see It always occur, when somebody is login or logout.

So far I haven't seen any severe problems.

**Comment by Roeda** [comment] 2024-09-02 21:10
same issue each time in each deployment when I added a user ( through URL/v2/users/human). no matter what I do, I always end up with :
zdb         | 2024-09-02 21:01:02.372 GMT [1556] ERROR:  could not obtain lock on row in relation "current_states"
zitadel     | time="2024-09-02T21:01:02Z" level=debug msg="unable to query current state" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/state.go:70" error="ERROR: could not obtain lock on row in relation \"current_states\" (SQLSTATE 55P03)" projection=auth.users3

have been trying for the past 2 months at this point, but I can't make zitadel work.

**Comment by fforootd** [comment] 2024-09-09 12:05
> same issue each time in each deployment when I added a user ( through URL/v2/users/human). no matter what I do, I always end up with : db | 2024-09-02 21:01:02.372 GMT [1556] ERROR: could not obtain lock on row in relation "current_states" zitadel | time="2024-09-02T21:01:02Z" level=debug msg="unable to query current state" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/state.go:70" error="ERROR: could not obtain lock on row in relation "current_states" (SQLSTATE 55P03)" projection=auth.users3
> 
> have been trying for the past 2 months at this point, but I can't make zitadel work.
> 
> (latest version of docker, docker compose and Fedora)

Usually, even if this message appears zitadel still works.

Can you share the exact version you use (zitadel prints that during startup) and how zitadel looks like when you try to access it?

**Comment by muhlemmer** [comment] 2024-11-01 09:55
We found the source of this errors was the milestones. More info can be found here: https://github.com/zitadel/zitadel/issues/8741. It should be fixed with: https://github.com/zitadel/zitadel/pull/8788.

**Closed by muhlemmer** 2024-11-01 09:55 UTC
Labels: bug, storage

**Comment by purple-emily** [comment] 2025-03-01 10:51
I hate to comment on a closed issue, but I have just attempted to deploy a totally new instance as a new user and I get the above error in my console logs when trying to login for the first time

**Comment by purple-emily** [comment] 2025-03-01 10:55
```
zitadel  | time="2025-03-01T10:47:58Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:588"
db       | 2025-03-01 10:48:50.734 UTC [1330] ERROR:  could not obtain lock on row in relation "current_states"
db       | 2025-03-01 10:48:50.734 UTC [1330] STATEMENT:  SELECT
db       |          aggregate_id
db       |          , aggregate_type
db       |          , "sequence"
db       |          , event_date
db       |          , "position"
db       |          , filter_offset
db       |      FROM 
db       |          projections.current_states
db       |      WHERE
db       |          instance_id = $1
db       |          AND projection_name = $2
db       |      FOR UPDATE NOWAIT;
zitadel  | time="2025-03-01T10:48:50Z" level=warning msg="missing translation" args="map[ChangeDate:2025-03-01 10:47:41.81005 +0000 UTC CreationDate:2025-03-01 10:47:41.81005 +0000 UTC DisplayName:ZITADEL Admin FirstName:ZITADEL LastEmail:<redacted my email> LastName:Admin LastPhone: LoginName:zitadel-admin@zitadel.zitadel.internal.<redacted url> LoginNames:[zitadel-admin@zitadel.zitadel.internal.<redacted url>] NickName: OrgID:309254524281880845 PreferredLoginName:zitadel-admin@zitadel.zitadel.internal.<redacted url>UserID:309254524282405133 UserName:zitadel-admin@zitadel.zitadel.internal.<redacted url>VerifiedEmail:<redacted my email>VerifiedPhone:]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/translator.go:173" error="message \"PasswordChange.Footer\" not found in language \"en\"" id=PasswordChange.Footer
zitadel  | time="2025-03-01T10:48:50Z" level=error msg="could not create email channel" caller="/home/runner/work/zitadel/zitadel/internal/notification/types/user_email.go:29" error="ID=QUERY-fwofw Message=Errors.SMTPConfig.NotFound Parent=(sql: no rows in result set)"
zitadel  | time="2025-03-01T10:51:41Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="https://zitadel.internal.<redacted url>" grpcStatus= httpStatus= instance=309254524281815309 isSystemUser=false method= org=309254524281880845 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=309254524282405133
zitadel  | time="2025-03-01T10:51:41Z" level=info msg="lock and generate signing key pair" caller="/home/runner/work/zitadel/zitadel/internal/api/oidc/key.go:397"
db       | 2025-03-01 10:52:39.326 UTC [53] LOG:  checkpoint starting: time
```

**Comment by muhlemmer** [comment] 2025-03-11 14:48
@purple-emily please open a [new issue](https://github.com/zitadel/zitadel/issues/new?template=BUG_REPORT.yaml) and fill in all the details in the template.
