### ISSUE TITLE
Generic OIDC and Oauth2 Configurable Prompt

### ISSUE THREAD

**Issue by expertonium** [zitadel/zitadel#6957] opened 2023-11-22 10:55 UTC
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

The prompt parameter hard-coded into the Generic OIDC provider causes Ping to issue an error and abort authentication. This issue was also noted specifically on Gitlab for Zitadel (https://gitlab.com/gitlab-org/gitlab/-/issues/377368), but perhaps the matter described there was rendered immaterial by the specific GitLab provider in Zitadel.

Hard-coding the prompt value to "select_account" is opinionated in a generic configuration.

This PR isolated the implementation in question, and has provided our team the only way, of itself, to support PingOne as a Generic OIDC.  The other possibility would be creating an entire Provider for Ping, but the ideal solution would the one described here.

https://github.com/zitadel/zitadel/pull/6854

### Describe your ideal solution

The "prompt" param (query string param), sent as a query string during Oauth2, should be made configurable in the Generic OIDC and Oauth2 Providers.

In addition to the normal valid prompt values being enumerated in a Select Menu ("select_account", "consent", etc), the option to not include the Prompt parameter at all would maximize compatibility.

Thanks!

### Environment

Self-hosted

**Comment by hifabienne** [comment] 2023-11-22 11:05
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by expertonium** [comment] 2023-11-28 16:41
It might bear discussion as to whether the prompt should just be pulled out of the generic OIDC provider entirely.  It is hard-coded to select_account, which is already odd, and different from the generic Oauth2 provider.  I wonder what good it does for any implementation?  Would it not be better to just allow such a thing to be appended to the url with an open ended "custom static param" if a user really needed it?  Such an approach would also allow the user to add whatever random param xyz system out there uses.

**Comment by hifabienne** [comment] 2024-07-24 08:59
I just realized that this issue is a duplicate of: https://github.com/zitadel/zitadel/issues/6599
Due to this I will close this issue, so we can track everything on the other.

**Closed by hifabienne** 2024-07-24 08:59 UTC
Labels: improvement, auth
