### ISSUE TITLE
OIDC IdP User Register does not allow to edit input fields

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4089] opened 2022-08-01 20:19 UTC
During an OIDC Register with an external IdP. In my case Google I am not able to edit the username.

Since a user with the name already existed i tried to change the name.

To reproduce:

1. Register a User with an OIDC IdP
2. Try to change any of the fields

**Comment by cyb3rd0g1** [comment] 2022-08-04 00:28
I'm not able to reproduce this with Dex. To clarify, are you changing the username while registering or once logged in to a registered user?

**Comment by cyb3rd0g1** [comment] 2022-08-04 02:25
Added a pass at resolution for the username field, it was being reset by the OIDC provided username

**Comment by livio-a** [comment] 2022-08-09 05:36
fixed with #4103

**Closed by livio-a** 2022-08-09 05:36 UTC
Labels: type: bug, state: ready, priority: critical
